//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from KayleeParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class KayleeParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		NUMERIC_LITERAL=1, STRING_LITERAL=2, BOOLEAN=3, INTEGER=4, UNSIGNED_INTEGER=5, 
		FLOAT=6, UNSIGNED_FLOAT=7, HEX_NUMBER=8, DTYPE_BIT=9, DTYPE_TINYINT=10, 
		DTYPE_INT=11, DTYPE_CHAR=12, DTYPE_TEXT=13, DTYPE_GUID=14, DTYPE_DATE=15, 
		DTYPE_VARBINARY=16, DTYPE_BINARY=17, DTYPE_ROWVERSION=18, FIELD_PARAMETER_DEFAULT_FUNCTION=19, 
		SCHEMA=20, ENTITY=21, FIELDS=22, KEYS=23, MUTATIONS=24, COMPUTED=25, DEFAULT=26, 
		PRIMARY=27, UNIQUE=28, REFERENCE=29, AUTO=30, INCREMENT=31, MAX=32, TRUE=33, 
		FALSE=34, SCOL=35, DOT=36, OPEN_PAR=37, CLOSE_PAR=38, OPEN_BLOCK=39, CLOSE_BLOCK=40, 
		COMMA=41, ASSIGN=42, MINUS=43, QUESTION_MARK=44, SCHEMA_ACCESSOR=45, ARROW=46, 
		IDENTIFIER=47, SINGLE_LINE_COMMENT=48, MULTI_LINE_COMMENT=49, WHITESPACE=50, 
		UNEXPECTED_CHAR=51;
	public const int
		RULE_parse = 0, RULE_error = 1, RULE_schema = 2, RULE_schemaBody = 3, 
		RULE_entity = 4, RULE_entityBody = 5, RULE_fields = 6, RULE_fieldsBody = 7, 
		RULE_field = 8, RULE_fieldBody = 9, RULE_fieldParameterComputed = 10, 
		RULE_fieldParameterComputedValue = 11, RULE_fieldParameterDefault = 12, 
		RULE_fieldParameterDefaultValue = 13, RULE_entityKeys = 14, RULE_entityKeysBody = 15, 
		RULE_entityKeyPrimary = 16, RULE_entityKeyUnique = 17, RULE_entityKeyReference = 18, 
		RULE_mutations = 19, RULE_mutationsBody = 20, RULE_mutation = 21, RULE_qualified = 22, 
		RULE_identifierList = 23, RULE_dtype = 24, RULE_dtypeIntAutoIncrement = 25, 
		RULE_dtypeTextSize = 26, RULE_dtypeVarbinarySize = 27, RULE_dtypeBinarySize = 28;
	public static readonly string[] ruleNames = {
		"parse", "error", "schema", "schemaBody", "entity", "entityBody", "fields", 
		"fieldsBody", "field", "fieldBody", "fieldParameterComputed", "fieldParameterComputedValue", 
		"fieldParameterDefault", "fieldParameterDefaultValue", "entityKeys", "entityKeysBody", 
		"entityKeyPrimary", "entityKeyUnique", "entityKeyReference", "mutations", 
		"mutationsBody", "mutation", "qualified", "identifierList", "dtype", "dtypeIntAutoIncrement", 
		"dtypeTextSize", "dtypeVarbinarySize", "dtypeBinarySize"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, null, null, null, "'BIT'", "'TINYINT'", 
		"'INT'", "'CHAR'", "'TEXT'", "'GUID'", "'DATE'", "'VARBINARY'", "'BINARY'", 
		"'ROWVERSION'", null, "'schema'", "'entity'", "'fields'", "'keys'", "'mutations'", 
		"'computed'", "'default'", "'primary'", "'unique'", "'reference'", "'AUTO'", 
		"'INCREMENT'", "'MAX'", "'true'", "'false'", "';'", "'.'", "'('", "')'", 
		"'{'", "'}'", "','", "'='", "'-'", "'?'", "'::'", "'=>'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "NUMERIC_LITERAL", "STRING_LITERAL", "BOOLEAN", "INTEGER", "UNSIGNED_INTEGER", 
		"FLOAT", "UNSIGNED_FLOAT", "HEX_NUMBER", "DTYPE_BIT", "DTYPE_TINYINT", 
		"DTYPE_INT", "DTYPE_CHAR", "DTYPE_TEXT", "DTYPE_GUID", "DTYPE_DATE", "DTYPE_VARBINARY", 
		"DTYPE_BINARY", "DTYPE_ROWVERSION", "FIELD_PARAMETER_DEFAULT_FUNCTION", 
		"SCHEMA", "ENTITY", "FIELDS", "KEYS", "MUTATIONS", "COMPUTED", "DEFAULT", 
		"PRIMARY", "UNIQUE", "REFERENCE", "AUTO", "INCREMENT", "MAX", "TRUE", 
		"FALSE", "SCOL", "DOT", "OPEN_PAR", "CLOSE_PAR", "OPEN_BLOCK", "CLOSE_BLOCK", 
		"COMMA", "ASSIGN", "MINUS", "QUESTION_MARK", "SCHEMA_ACCESSOR", "ARROW", 
		"IDENTIFIER", "SINGLE_LINE_COMMENT", "MULTI_LINE_COMMENT", "WHITESPACE", 
		"UNEXPECTED_CHAR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "KayleeParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static KayleeParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public KayleeParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public KayleeParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ParseContext : ParserRuleContext {
		public ITerminalNode Eof() { return GetToken(KayleeParser.Eof, 0); }
		public SchemaContext[] schema() {
			return GetRuleContexts<SchemaContext>();
		}
		public SchemaContext schema(int i) {
			return GetRuleContext<SchemaContext>(i);
		}
		public ErrorContext[] error() {
			return GetRuleContexts<ErrorContext>();
		}
		public ErrorContext error(int i) {
			return GetRuleContext<ErrorContext>(i);
		}
		public ParseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parse; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterParse(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitParse(this);
		}
	}

	[RuleVersion(0)]
	public ParseContext parse() {
		ParseContext _localctx = new ParseContext(Context, State);
		EnterRule(_localctx, 0, RULE_parse);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 62;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==SCHEMA || _la==UNEXPECTED_CHAR) {
				{
				State = 60;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case SCHEMA:
					{
					State = 58; schema();
					}
					break;
				case UNEXPECTED_CHAR:
					{
					State = 59; error();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 64;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 65; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ErrorContext : ParserRuleContext {
		public IToken _UNEXPECTED_CHAR;
		public ITerminalNode UNEXPECTED_CHAR() { return GetToken(KayleeParser.UNEXPECTED_CHAR, 0); }
		public ErrorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_error; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterError(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitError(this);
		}
	}

	[RuleVersion(0)]
	public ErrorContext error() {
		ErrorContext _localctx = new ErrorContext(Context, State);
		EnterRule(_localctx, 2, RULE_error);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 67; _localctx._UNEXPECTED_CHAR = Match(UNEXPECTED_CHAR);

				throw new FormatException("UNEXPECTED_CHAR=" + (_localctx._UNEXPECTED_CHAR!=null?_localctx._UNEXPECTED_CHAR.Text:null));

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SchemaContext : ParserRuleContext {
		public ITerminalNode SCHEMA() { return GetToken(KayleeParser.SCHEMA, 0); }
		public ITerminalNode IDENTIFIER() { return GetToken(KayleeParser.IDENTIFIER, 0); }
		public ITerminalNode OPEN_BLOCK() { return GetToken(KayleeParser.OPEN_BLOCK, 0); }
		public SchemaBodyContext schemaBody() {
			return GetRuleContext<SchemaBodyContext>(0);
		}
		public ITerminalNode CLOSE_BLOCK() { return GetToken(KayleeParser.CLOSE_BLOCK, 0); }
		public SchemaContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_schema; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterSchema(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitSchema(this);
		}
	}

	[RuleVersion(0)]
	public SchemaContext schema() {
		SchemaContext _localctx = new SchemaContext(Context, State);
		EnterRule(_localctx, 4, RULE_schema);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 70; Match(SCHEMA);
			State = 71; Match(IDENTIFIER);
			State = 72; Match(OPEN_BLOCK);
			State = 73; schemaBody();
			State = 74; Match(CLOSE_BLOCK);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SchemaBodyContext : ParserRuleContext {
		public EntityContext[] entity() {
			return GetRuleContexts<EntityContext>();
		}
		public EntityContext entity(int i) {
			return GetRuleContext<EntityContext>(i);
		}
		public SchemaBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_schemaBody; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterSchemaBody(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitSchemaBody(this);
		}
	}

	[RuleVersion(0)]
	public SchemaBodyContext schemaBody() {
		SchemaBodyContext _localctx = new SchemaBodyContext(Context, State);
		EnterRule(_localctx, 6, RULE_schemaBody);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 79;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==ENTITY) {
				{
				{
				State = 76; entity();
				}
				}
				State = 81;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EntityContext : ParserRuleContext {
		public ITerminalNode ENTITY() { return GetToken(KayleeParser.ENTITY, 0); }
		public ITerminalNode IDENTIFIER() { return GetToken(KayleeParser.IDENTIFIER, 0); }
		public ITerminalNode OPEN_BLOCK() { return GetToken(KayleeParser.OPEN_BLOCK, 0); }
		public EntityBodyContext entityBody() {
			return GetRuleContext<EntityBodyContext>(0);
		}
		public ITerminalNode CLOSE_BLOCK() { return GetToken(KayleeParser.CLOSE_BLOCK, 0); }
		public EntityContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_entity; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterEntity(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitEntity(this);
		}
	}

	[RuleVersion(0)]
	public EntityContext entity() {
		EntityContext _localctx = new EntityContext(Context, State);
		EnterRule(_localctx, 8, RULE_entity);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 82; Match(ENTITY);
			State = 83; Match(IDENTIFIER);
			State = 84; Match(OPEN_BLOCK);
			State = 85; entityBody();
			State = 86; Match(CLOSE_BLOCK);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EntityBodyContext : ParserRuleContext {
		public FieldsContext[] fields() {
			return GetRuleContexts<FieldsContext>();
		}
		public FieldsContext fields(int i) {
			return GetRuleContext<FieldsContext>(i);
		}
		public EntityKeysContext[] entityKeys() {
			return GetRuleContexts<EntityKeysContext>();
		}
		public EntityKeysContext entityKeys(int i) {
			return GetRuleContext<EntityKeysContext>(i);
		}
		public MutationsContext[] mutations() {
			return GetRuleContexts<MutationsContext>();
		}
		public MutationsContext mutations(int i) {
			return GetRuleContext<MutationsContext>(i);
		}
		public EntityContext[] entity() {
			return GetRuleContexts<EntityContext>();
		}
		public EntityContext entity(int i) {
			return GetRuleContext<EntityContext>(i);
		}
		public EntityBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_entityBody; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterEntityBody(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitEntityBody(this);
		}
	}

	[RuleVersion(0)]
	public EntityBodyContext entityBody() {
		EntityBodyContext _localctx = new EntityBodyContext(Context, State);
		EnterRule(_localctx, 10, RULE_entityBody);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 94;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << ENTITY) | (1L << FIELDS) | (1L << KEYS) | (1L << MUTATIONS))) != 0)) {
				{
				State = 92;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case FIELDS:
					{
					State = 88; fields();
					}
					break;
				case KEYS:
					{
					State = 89; entityKeys();
					}
					break;
				case MUTATIONS:
					{
					State = 90; mutations();
					}
					break;
				case ENTITY:
					{
					State = 91; entity();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 96;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FieldsContext : ParserRuleContext {
		public ITerminalNode FIELDS() { return GetToken(KayleeParser.FIELDS, 0); }
		public ITerminalNode OPEN_BLOCK() { return GetToken(KayleeParser.OPEN_BLOCK, 0); }
		public FieldsBodyContext fieldsBody() {
			return GetRuleContext<FieldsBodyContext>(0);
		}
		public ITerminalNode CLOSE_BLOCK() { return GetToken(KayleeParser.CLOSE_BLOCK, 0); }
		public FieldsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fields; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterFields(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitFields(this);
		}
	}

	[RuleVersion(0)]
	public FieldsContext fields() {
		FieldsContext _localctx = new FieldsContext(Context, State);
		EnterRule(_localctx, 12, RULE_fields);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 97; Match(FIELDS);
			State = 98; Match(OPEN_BLOCK);
			State = 99; fieldsBody();
			State = 100; Match(CLOSE_BLOCK);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FieldsBodyContext : ParserRuleContext {
		public FieldContext[] field() {
			return GetRuleContexts<FieldContext>();
		}
		public FieldContext field(int i) {
			return GetRuleContext<FieldContext>(i);
		}
		public FieldsBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fieldsBody; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterFieldsBody(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitFieldsBody(this);
		}
	}

	[RuleVersion(0)]
	public FieldsBodyContext fieldsBody() {
		FieldsBodyContext _localctx = new FieldsBodyContext(Context, State);
		EnterRule(_localctx, 14, RULE_fieldsBody);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 105;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==IDENTIFIER) {
				{
				{
				State = 102; field();
				}
				}
				State = 107;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FieldContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(KayleeParser.IDENTIFIER, 0); }
		public DtypeContext dtype() {
			return GetRuleContext<DtypeContext>(0);
		}
		public ITerminalNode OPEN_BLOCK() { return GetToken(KayleeParser.OPEN_BLOCK, 0); }
		public FieldBodyContext fieldBody() {
			return GetRuleContext<FieldBodyContext>(0);
		}
		public ITerminalNode CLOSE_BLOCK() { return GetToken(KayleeParser.CLOSE_BLOCK, 0); }
		public ITerminalNode SCOL() { return GetToken(KayleeParser.SCOL, 0); }
		public ITerminalNode QUESTION_MARK() { return GetToken(KayleeParser.QUESTION_MARK, 0); }
		public FieldContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_field; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterField(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitField(this);
		}
	}

	[RuleVersion(0)]
	public FieldContext field() {
		FieldContext _localctx = new FieldContext(Context, State);
		EnterRule(_localctx, 16, RULE_field);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 108; Match(IDENTIFIER);
			State = 110;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==QUESTION_MARK) {
				{
				State = 109; Match(QUESTION_MARK);
				}
			}

			State = 112; dtype();
			State = 118;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case OPEN_BLOCK:
				{
				State = 113; Match(OPEN_BLOCK);
				State = 114; fieldBody();
				State = 115; Match(CLOSE_BLOCK);
				}
				break;
			case SCOL:
				{
				State = 117; Match(SCOL);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FieldBodyContext : ParserRuleContext {
		public FieldParameterComputedContext[] fieldParameterComputed() {
			return GetRuleContexts<FieldParameterComputedContext>();
		}
		public FieldParameterComputedContext fieldParameterComputed(int i) {
			return GetRuleContext<FieldParameterComputedContext>(i);
		}
		public FieldParameterDefaultContext[] fieldParameterDefault() {
			return GetRuleContexts<FieldParameterDefaultContext>();
		}
		public FieldParameterDefaultContext fieldParameterDefault(int i) {
			return GetRuleContext<FieldParameterDefaultContext>(i);
		}
		public FieldBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fieldBody; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterFieldBody(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitFieldBody(this);
		}
	}

	[RuleVersion(0)]
	public FieldBodyContext fieldBody() {
		FieldBodyContext _localctx = new FieldBodyContext(Context, State);
		EnterRule(_localctx, 18, RULE_fieldBody);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 124;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMPUTED || _la==DEFAULT) {
				{
				State = 122;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case COMPUTED:
					{
					State = 120; fieldParameterComputed();
					}
					break;
				case DEFAULT:
					{
					State = 121; fieldParameterDefault();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 126;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FieldParameterComputedContext : ParserRuleContext {
		public ITerminalNode COMPUTED() { return GetToken(KayleeParser.COMPUTED, 0); }
		public ITerminalNode ASSIGN() { return GetToken(KayleeParser.ASSIGN, 0); }
		public FieldParameterComputedValueContext fieldParameterComputedValue() {
			return GetRuleContext<FieldParameterComputedValueContext>(0);
		}
		public ITerminalNode SCOL() { return GetToken(KayleeParser.SCOL, 0); }
		public FieldParameterComputedContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fieldParameterComputed; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterFieldParameterComputed(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitFieldParameterComputed(this);
		}
	}

	[RuleVersion(0)]
	public FieldParameterComputedContext fieldParameterComputed() {
		FieldParameterComputedContext _localctx = new FieldParameterComputedContext(Context, State);
		EnterRule(_localctx, 20, RULE_fieldParameterComputed);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 127; Match(COMPUTED);
			State = 128; Match(ASSIGN);
			State = 129; fieldParameterComputedValue();
			State = 130; Match(SCOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FieldParameterComputedValueContext : ParserRuleContext {
		public ITerminalNode BOOLEAN() { return GetToken(KayleeParser.BOOLEAN, 0); }
		public FieldParameterComputedValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fieldParameterComputedValue; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterFieldParameterComputedValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitFieldParameterComputedValue(this);
		}
	}

	[RuleVersion(0)]
	public FieldParameterComputedValueContext fieldParameterComputedValue() {
		FieldParameterComputedValueContext _localctx = new FieldParameterComputedValueContext(Context, State);
		EnterRule(_localctx, 22, RULE_fieldParameterComputedValue);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 132; Match(BOOLEAN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FieldParameterDefaultContext : ParserRuleContext {
		public ITerminalNode DEFAULT() { return GetToken(KayleeParser.DEFAULT, 0); }
		public ITerminalNode ASSIGN() { return GetToken(KayleeParser.ASSIGN, 0); }
		public FieldParameterDefaultValueContext fieldParameterDefaultValue() {
			return GetRuleContext<FieldParameterDefaultValueContext>(0);
		}
		public ITerminalNode SCOL() { return GetToken(KayleeParser.SCOL, 0); }
		public FieldParameterDefaultContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fieldParameterDefault; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterFieldParameterDefault(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitFieldParameterDefault(this);
		}
	}

	[RuleVersion(0)]
	public FieldParameterDefaultContext fieldParameterDefault() {
		FieldParameterDefaultContext _localctx = new FieldParameterDefaultContext(Context, State);
		EnterRule(_localctx, 24, RULE_fieldParameterDefault);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 134; Match(DEFAULT);
			State = 135; Match(ASSIGN);
			State = 136; fieldParameterDefaultValue();
			State = 137; Match(SCOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FieldParameterDefaultValueContext : ParserRuleContext {
		public ITerminalNode NUMERIC_LITERAL() { return GetToken(KayleeParser.NUMERIC_LITERAL, 0); }
		public ITerminalNode STRING_LITERAL() { return GetToken(KayleeParser.STRING_LITERAL, 0); }
		public ITerminalNode FIELD_PARAMETER_DEFAULT_FUNCTION() { return GetToken(KayleeParser.FIELD_PARAMETER_DEFAULT_FUNCTION, 0); }
		public ITerminalNode OPEN_PAR() { return GetToken(KayleeParser.OPEN_PAR, 0); }
		public ITerminalNode CLOSE_PAR() { return GetToken(KayleeParser.CLOSE_PAR, 0); }
		public FieldParameterDefaultValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fieldParameterDefaultValue; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterFieldParameterDefaultValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitFieldParameterDefaultValue(this);
		}
	}

	[RuleVersion(0)]
	public FieldParameterDefaultValueContext fieldParameterDefaultValue() {
		FieldParameterDefaultValueContext _localctx = new FieldParameterDefaultValueContext(Context, State);
		EnterRule(_localctx, 26, RULE_fieldParameterDefaultValue);
		try {
			State = 144;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NUMERIC_LITERAL:
				EnterOuterAlt(_localctx, 1);
				{
				State = 139; Match(NUMERIC_LITERAL);
				}
				break;
			case STRING_LITERAL:
				EnterOuterAlt(_localctx, 2);
				{
				State = 140; Match(STRING_LITERAL);
				}
				break;
			case FIELD_PARAMETER_DEFAULT_FUNCTION:
				EnterOuterAlt(_localctx, 3);
				{
				State = 141; Match(FIELD_PARAMETER_DEFAULT_FUNCTION);
				State = 142; Match(OPEN_PAR);
				State = 143; Match(CLOSE_PAR);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EntityKeysContext : ParserRuleContext {
		public ITerminalNode KEYS() { return GetToken(KayleeParser.KEYS, 0); }
		public ITerminalNode OPEN_BLOCK() { return GetToken(KayleeParser.OPEN_BLOCK, 0); }
		public EntityKeysBodyContext entityKeysBody() {
			return GetRuleContext<EntityKeysBodyContext>(0);
		}
		public ITerminalNode CLOSE_BLOCK() { return GetToken(KayleeParser.CLOSE_BLOCK, 0); }
		public EntityKeysContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_entityKeys; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterEntityKeys(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitEntityKeys(this);
		}
	}

	[RuleVersion(0)]
	public EntityKeysContext entityKeys() {
		EntityKeysContext _localctx = new EntityKeysContext(Context, State);
		EnterRule(_localctx, 28, RULE_entityKeys);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 146; Match(KEYS);
			State = 147; Match(OPEN_BLOCK);
			State = 148; entityKeysBody();
			State = 149; Match(CLOSE_BLOCK);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EntityKeysBodyContext : ParserRuleContext {
		public EntityKeyPrimaryContext[] entityKeyPrimary() {
			return GetRuleContexts<EntityKeyPrimaryContext>();
		}
		public EntityKeyPrimaryContext entityKeyPrimary(int i) {
			return GetRuleContext<EntityKeyPrimaryContext>(i);
		}
		public EntityKeyUniqueContext[] entityKeyUnique() {
			return GetRuleContexts<EntityKeyUniqueContext>();
		}
		public EntityKeyUniqueContext entityKeyUnique(int i) {
			return GetRuleContext<EntityKeyUniqueContext>(i);
		}
		public EntityKeyReferenceContext[] entityKeyReference() {
			return GetRuleContexts<EntityKeyReferenceContext>();
		}
		public EntityKeyReferenceContext entityKeyReference(int i) {
			return GetRuleContext<EntityKeyReferenceContext>(i);
		}
		public EntityKeysBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_entityKeysBody; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterEntityKeysBody(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitEntityKeysBody(this);
		}
	}

	[RuleVersion(0)]
	public EntityKeysBodyContext entityKeysBody() {
		EntityKeysBodyContext _localctx = new EntityKeysBodyContext(Context, State);
		EnterRule(_localctx, 30, RULE_entityKeysBody);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 156;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << PRIMARY) | (1L << UNIQUE) | (1L << REFERENCE))) != 0)) {
				{
				State = 154;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case PRIMARY:
					{
					State = 151; entityKeyPrimary();
					}
					break;
				case UNIQUE:
					{
					State = 152; entityKeyUnique();
					}
					break;
				case REFERENCE:
					{
					State = 153; entityKeyReference();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 158;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EntityKeyPrimaryContext : ParserRuleContext {
		public ITerminalNode PRIMARY() { return GetToken(KayleeParser.PRIMARY, 0); }
		public ITerminalNode ASSIGN() { return GetToken(KayleeParser.ASSIGN, 0); }
		public IdentifierListContext identifierList() {
			return GetRuleContext<IdentifierListContext>(0);
		}
		public ITerminalNode SCOL() { return GetToken(KayleeParser.SCOL, 0); }
		public EntityKeyPrimaryContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_entityKeyPrimary; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterEntityKeyPrimary(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitEntityKeyPrimary(this);
		}
	}

	[RuleVersion(0)]
	public EntityKeyPrimaryContext entityKeyPrimary() {
		EntityKeyPrimaryContext _localctx = new EntityKeyPrimaryContext(Context, State);
		EnterRule(_localctx, 32, RULE_entityKeyPrimary);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 159; Match(PRIMARY);
			State = 160; Match(ASSIGN);
			State = 161; identifierList();
			State = 162; Match(SCOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EntityKeyUniqueContext : ParserRuleContext {
		public ITerminalNode UNIQUE() { return GetToken(KayleeParser.UNIQUE, 0); }
		public ITerminalNode OPEN_PAR() { return GetToken(KayleeParser.OPEN_PAR, 0); }
		public IdentifierListContext identifierList() {
			return GetRuleContext<IdentifierListContext>(0);
		}
		public ITerminalNode CLOSE_PAR() { return GetToken(KayleeParser.CLOSE_PAR, 0); }
		public ITerminalNode SCOL() { return GetToken(KayleeParser.SCOL, 0); }
		public EntityKeyUniqueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_entityKeyUnique; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterEntityKeyUnique(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitEntityKeyUnique(this);
		}
	}

	[RuleVersion(0)]
	public EntityKeyUniqueContext entityKeyUnique() {
		EntityKeyUniqueContext _localctx = new EntityKeyUniqueContext(Context, State);
		EnterRule(_localctx, 34, RULE_entityKeyUnique);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 164; Match(UNIQUE);
			State = 165; Match(OPEN_PAR);
			State = 166; identifierList();
			State = 167; Match(CLOSE_PAR);
			State = 168; Match(SCOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EntityKeyReferenceContext : ParserRuleContext {
		public ITerminalNode REFERENCE() { return GetToken(KayleeParser.REFERENCE, 0); }
		public ITerminalNode[] OPEN_PAR() { return GetTokens(KayleeParser.OPEN_PAR); }
		public ITerminalNode OPEN_PAR(int i) {
			return GetToken(KayleeParser.OPEN_PAR, i);
		}
		public IdentifierListContext[] identifierList() {
			return GetRuleContexts<IdentifierListContext>();
		}
		public IdentifierListContext identifierList(int i) {
			return GetRuleContext<IdentifierListContext>(i);
		}
		public ITerminalNode[] CLOSE_PAR() { return GetTokens(KayleeParser.CLOSE_PAR); }
		public ITerminalNode CLOSE_PAR(int i) {
			return GetToken(KayleeParser.CLOSE_PAR, i);
		}
		public ITerminalNode ARROW() { return GetToken(KayleeParser.ARROW, 0); }
		public QualifiedContext qualified() {
			return GetRuleContext<QualifiedContext>(0);
		}
		public ITerminalNode SCOL() { return GetToken(KayleeParser.SCOL, 0); }
		public EntityKeyReferenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_entityKeyReference; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterEntityKeyReference(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitEntityKeyReference(this);
		}
	}

	[RuleVersion(0)]
	public EntityKeyReferenceContext entityKeyReference() {
		EntityKeyReferenceContext _localctx = new EntityKeyReferenceContext(Context, State);
		EnterRule(_localctx, 36, RULE_entityKeyReference);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 170; Match(REFERENCE);
			State = 171; Match(OPEN_PAR);
			State = 172; identifierList();
			State = 173; Match(CLOSE_PAR);
			State = 174; Match(ARROW);
			State = 175; qualified();
			State = 176; Match(OPEN_PAR);
			State = 177; identifierList();
			State = 178; Match(CLOSE_PAR);
			State = 179; Match(SCOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MutationsContext : ParserRuleContext {
		public ITerminalNode MUTATIONS() { return GetToken(KayleeParser.MUTATIONS, 0); }
		public ITerminalNode OPEN_BLOCK() { return GetToken(KayleeParser.OPEN_BLOCK, 0); }
		public MutationsBodyContext mutationsBody() {
			return GetRuleContext<MutationsBodyContext>(0);
		}
		public ITerminalNode CLOSE_BLOCK() { return GetToken(KayleeParser.CLOSE_BLOCK, 0); }
		public MutationsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mutations; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterMutations(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitMutations(this);
		}
	}

	[RuleVersion(0)]
	public MutationsContext mutations() {
		MutationsContext _localctx = new MutationsContext(Context, State);
		EnterRule(_localctx, 38, RULE_mutations);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 181; Match(MUTATIONS);
			State = 182; Match(OPEN_BLOCK);
			State = 183; mutationsBody();
			State = 184; Match(CLOSE_BLOCK);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MutationsBodyContext : ParserRuleContext {
		public MutationContext[] mutation() {
			return GetRuleContexts<MutationContext>();
		}
		public MutationContext mutation(int i) {
			return GetRuleContext<MutationContext>(i);
		}
		public MutationsBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mutationsBody; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterMutationsBody(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitMutationsBody(this);
		}
	}

	[RuleVersion(0)]
	public MutationsBodyContext mutationsBody() {
		MutationsBodyContext _localctx = new MutationsBodyContext(Context, State);
		EnterRule(_localctx, 40, RULE_mutationsBody);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 189;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==IDENTIFIER) {
				{
				{
				State = 186; mutation();
				}
				}
				State = 191;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MutationContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(KayleeParser.IDENTIFIER, 0); }
		public ITerminalNode OPEN_PAR() { return GetToken(KayleeParser.OPEN_PAR, 0); }
		public IdentifierListContext identifierList() {
			return GetRuleContext<IdentifierListContext>(0);
		}
		public ITerminalNode CLOSE_PAR() { return GetToken(KayleeParser.CLOSE_PAR, 0); }
		public ITerminalNode SCOL() { return GetToken(KayleeParser.SCOL, 0); }
		public MutationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mutation; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterMutation(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitMutation(this);
		}
	}

	[RuleVersion(0)]
	public MutationContext mutation() {
		MutationContext _localctx = new MutationContext(Context, State);
		EnterRule(_localctx, 42, RULE_mutation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 192; Match(IDENTIFIER);
			State = 193; Match(OPEN_PAR);
			State = 194; identifierList();
			State = 195; Match(CLOSE_PAR);
			State = 196; Match(SCOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class QualifiedContext : ParserRuleContext {
		public ITerminalNode[] IDENTIFIER() { return GetTokens(KayleeParser.IDENTIFIER); }
		public ITerminalNode IDENTIFIER(int i) {
			return GetToken(KayleeParser.IDENTIFIER, i);
		}
		public ITerminalNode SCHEMA_ACCESSOR() { return GetToken(KayleeParser.SCHEMA_ACCESSOR, 0); }
		public ITerminalNode[] DOT() { return GetTokens(KayleeParser.DOT); }
		public ITerminalNode DOT(int i) {
			return GetToken(KayleeParser.DOT, i);
		}
		public QualifiedContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_qualified; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterQualified(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitQualified(this);
		}
	}

	[RuleVersion(0)]
	public QualifiedContext qualified() {
		QualifiedContext _localctx = new QualifiedContext(Context, State);
		EnterRule(_localctx, 44, RULE_qualified);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 200;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
			case 1:
				{
				State = 198; Match(IDENTIFIER);
				State = 199; Match(SCHEMA_ACCESSOR);
				}
				break;
			}
			State = 202; Match(IDENTIFIER);
			State = 207;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==DOT) {
				{
				{
				State = 203; Match(DOT);
				State = 204; Match(IDENTIFIER);
				}
				}
				State = 209;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdentifierListContext : ParserRuleContext {
		public ITerminalNode[] IDENTIFIER() { return GetTokens(KayleeParser.IDENTIFIER); }
		public ITerminalNode IDENTIFIER(int i) {
			return GetToken(KayleeParser.IDENTIFIER, i);
		}
		public ITerminalNode[] COMMA() { return GetTokens(KayleeParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(KayleeParser.COMMA, i);
		}
		public IdentifierListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_identifierList; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterIdentifierList(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitIdentifierList(this);
		}
	}

	[RuleVersion(0)]
	public IdentifierListContext identifierList() {
		IdentifierListContext _localctx = new IdentifierListContext(Context, State);
		EnterRule(_localctx, 46, RULE_identifierList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 210; Match(IDENTIFIER);
			State = 215;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 211; Match(COMMA);
				State = 212; Match(IDENTIFIER);
				}
				}
				State = 217;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DtypeContext : ParserRuleContext {
		public ITerminalNode DTYPE_BIT() { return GetToken(KayleeParser.DTYPE_BIT, 0); }
		public ITerminalNode DTYPE_TINYINT() { return GetToken(KayleeParser.DTYPE_TINYINT, 0); }
		public ITerminalNode DTYPE_INT() { return GetToken(KayleeParser.DTYPE_INT, 0); }
		public DtypeIntAutoIncrementContext dtypeIntAutoIncrement() {
			return GetRuleContext<DtypeIntAutoIncrementContext>(0);
		}
		public ITerminalNode DTYPE_CHAR() { return GetToken(KayleeParser.DTYPE_CHAR, 0); }
		public ITerminalNode DTYPE_TEXT() { return GetToken(KayleeParser.DTYPE_TEXT, 0); }
		public ITerminalNode OPEN_PAR() { return GetToken(KayleeParser.OPEN_PAR, 0); }
		public DtypeTextSizeContext dtypeTextSize() {
			return GetRuleContext<DtypeTextSizeContext>(0);
		}
		public ITerminalNode CLOSE_PAR() { return GetToken(KayleeParser.CLOSE_PAR, 0); }
		public ITerminalNode DTYPE_GUID() { return GetToken(KayleeParser.DTYPE_GUID, 0); }
		public ITerminalNode DTYPE_DATE() { return GetToken(KayleeParser.DTYPE_DATE, 0); }
		public ITerminalNode DTYPE_VARBINARY() { return GetToken(KayleeParser.DTYPE_VARBINARY, 0); }
		public DtypeVarbinarySizeContext dtypeVarbinarySize() {
			return GetRuleContext<DtypeVarbinarySizeContext>(0);
		}
		public ITerminalNode DTYPE_BINARY() { return GetToken(KayleeParser.DTYPE_BINARY, 0); }
		public DtypeBinarySizeContext dtypeBinarySize() {
			return GetRuleContext<DtypeBinarySizeContext>(0);
		}
		public ITerminalNode DTYPE_ROWVERSION() { return GetToken(KayleeParser.DTYPE_ROWVERSION, 0); }
		public DtypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dtype; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterDtype(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitDtype(this);
		}
	}

	[RuleVersion(0)]
	public DtypeContext dtype() {
		DtypeContext _localctx = new DtypeContext(Context, State);
		EnterRule(_localctx, 48, RULE_dtype);
		int _la;
		try {
			State = 243;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case DTYPE_BIT:
				EnterOuterAlt(_localctx, 1);
				{
				State = 218; Match(DTYPE_BIT);
				}
				break;
			case DTYPE_TINYINT:
				EnterOuterAlt(_localctx, 2);
				{
				State = 219; Match(DTYPE_TINYINT);
				}
				break;
			case DTYPE_INT:
				EnterOuterAlt(_localctx, 3);
				{
				State = 220; Match(DTYPE_INT);
				State = 222;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==AUTO) {
					{
					State = 221; dtypeIntAutoIncrement();
					}
				}

				}
				break;
			case DTYPE_CHAR:
				EnterOuterAlt(_localctx, 4);
				{
				State = 224; Match(DTYPE_CHAR);
				}
				break;
			case DTYPE_TEXT:
				EnterOuterAlt(_localctx, 5);
				{
				State = 225; Match(DTYPE_TEXT);
				State = 226; Match(OPEN_PAR);
				State = 227; dtypeTextSize();
				State = 228; Match(CLOSE_PAR);
				}
				break;
			case DTYPE_GUID:
				EnterOuterAlt(_localctx, 6);
				{
				State = 230; Match(DTYPE_GUID);
				}
				break;
			case DTYPE_DATE:
				EnterOuterAlt(_localctx, 7);
				{
				State = 231; Match(DTYPE_DATE);
				}
				break;
			case DTYPE_VARBINARY:
				EnterOuterAlt(_localctx, 8);
				{
				State = 232; Match(DTYPE_VARBINARY);
				State = 233; Match(OPEN_PAR);
				State = 234; dtypeVarbinarySize();
				State = 235; Match(CLOSE_PAR);
				}
				break;
			case DTYPE_BINARY:
				EnterOuterAlt(_localctx, 9);
				{
				State = 237; Match(DTYPE_BINARY);
				State = 238; Match(OPEN_PAR);
				State = 239; dtypeBinarySize();
				State = 240; Match(CLOSE_PAR);
				}
				break;
			case DTYPE_ROWVERSION:
				EnterOuterAlt(_localctx, 10);
				{
				State = 242; Match(DTYPE_ROWVERSION);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DtypeIntAutoIncrementContext : ParserRuleContext {
		public ITerminalNode AUTO() { return GetToken(KayleeParser.AUTO, 0); }
		public ITerminalNode INCREMENT() { return GetToken(KayleeParser.INCREMENT, 0); }
		public DtypeIntAutoIncrementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dtypeIntAutoIncrement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterDtypeIntAutoIncrement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitDtypeIntAutoIncrement(this);
		}
	}

	[RuleVersion(0)]
	public DtypeIntAutoIncrementContext dtypeIntAutoIncrement() {
		DtypeIntAutoIncrementContext _localctx = new DtypeIntAutoIncrementContext(Context, State);
		EnterRule(_localctx, 50, RULE_dtypeIntAutoIncrement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 245; Match(AUTO);
			State = 246; Match(INCREMENT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DtypeTextSizeContext : ParserRuleContext {
		public ITerminalNode UNSIGNED_INTEGER() { return GetToken(KayleeParser.UNSIGNED_INTEGER, 0); }
		public ITerminalNode MAX() { return GetToken(KayleeParser.MAX, 0); }
		public DtypeTextSizeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dtypeTextSize; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterDtypeTextSize(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitDtypeTextSize(this);
		}
	}

	[RuleVersion(0)]
	public DtypeTextSizeContext dtypeTextSize() {
		DtypeTextSizeContext _localctx = new DtypeTextSizeContext(Context, State);
		EnterRule(_localctx, 52, RULE_dtypeTextSize);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 248;
			_la = TokenStream.LA(1);
			if ( !(_la==UNSIGNED_INTEGER || _la==MAX) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DtypeVarbinarySizeContext : ParserRuleContext {
		public ITerminalNode UNSIGNED_INTEGER() { return GetToken(KayleeParser.UNSIGNED_INTEGER, 0); }
		public ITerminalNode MAX() { return GetToken(KayleeParser.MAX, 0); }
		public DtypeVarbinarySizeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dtypeVarbinarySize; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterDtypeVarbinarySize(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitDtypeVarbinarySize(this);
		}
	}

	[RuleVersion(0)]
	public DtypeVarbinarySizeContext dtypeVarbinarySize() {
		DtypeVarbinarySizeContext _localctx = new DtypeVarbinarySizeContext(Context, State);
		EnterRule(_localctx, 54, RULE_dtypeVarbinarySize);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 250;
			_la = TokenStream.LA(1);
			if ( !(_la==UNSIGNED_INTEGER || _la==MAX) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DtypeBinarySizeContext : ParserRuleContext {
		public ITerminalNode UNSIGNED_INTEGER() { return GetToken(KayleeParser.UNSIGNED_INTEGER, 0); }
		public DtypeBinarySizeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dtypeBinarySize; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterDtypeBinarySize(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitDtypeBinarySize(this);
		}
	}

	[RuleVersion(0)]
	public DtypeBinarySizeContext dtypeBinarySize() {
		DtypeBinarySizeContext _localctx = new DtypeBinarySizeContext(Context, State);
		EnterRule(_localctx, 56, RULE_dtypeBinarySize);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 252; Match(UNSIGNED_INTEGER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x35', '\x101', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x3', '\x2', '\x3', '\x2', '\a', 
		'\x2', '?', '\n', '\x2', '\f', '\x2', '\xE', '\x2', '\x42', '\v', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x5', '\a', '\x5', 'P', '\n', '\x5', '\f', '\x5', 
		'\xE', '\x5', 'S', '\v', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\a', '\a', '_', '\n', '\a', '\f', '\a', '\xE', '\a', 
		'\x62', '\v', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\t', '\a', '\t', 'j', '\n', '\t', '\f', '\t', '\xE', 
		'\t', 'm', '\v', '\t', '\x3', '\n', '\x3', '\n', '\x5', '\n', 'q', '\n', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x5', '\n', 'y', '\n', '\n', '\x3', '\v', '\x3', '\v', '\a', 
		'\v', '}', '\n', '\v', '\f', '\v', '\xE', '\v', '\x80', '\v', '\v', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', 
		'\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x5', '\xF', '\x93', '\n', '\xF', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\a', '\x11', '\x9D', '\n', '\x11', '\f', '\x11', '\xE', 
		'\x11', '\xA0', '\v', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', 
		'\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', 
		'\a', '\x16', '\xBE', '\n', '\x16', '\f', '\x16', '\xE', '\x16', '\xC1', 
		'\v', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x5', '\x18', 
		'\xCB', '\n', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\a', 
		'\x18', '\xD0', '\n', '\x18', '\f', '\x18', '\xE', '\x18', '\xD3', '\v', 
		'\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\a', '\x19', '\xD8', 
		'\n', '\x19', '\f', '\x19', '\xE', '\x19', '\xDB', '\v', '\x19', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x5', '\x1A', '\xE1', 
		'\n', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', 
		'\x5', '\x1A', '\xF6', '\n', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', 
		'\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x3', 
		'\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x2', '\x2', '\x1F', '\x2', '\x4', 
		'\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', '\x14', '\x16', '\x18', 
		'\x1A', '\x1C', '\x1E', ' ', '\"', '$', '&', '(', '*', ',', '.', '\x30', 
		'\x32', '\x34', '\x36', '\x38', ':', '\x2', '\x3', '\x4', '\x2', '\a', 
		'\a', '\"', '\"', '\x2', '\x102', '\x2', '@', '\x3', '\x2', '\x2', '\x2', 
		'\x4', '\x45', '\x3', '\x2', '\x2', '\x2', '\x6', 'H', '\x3', '\x2', '\x2', 
		'\x2', '\b', 'Q', '\x3', '\x2', '\x2', '\x2', '\n', 'T', '\x3', '\x2', 
		'\x2', '\x2', '\f', '`', '\x3', '\x2', '\x2', '\x2', '\xE', '\x63', '\x3', 
		'\x2', '\x2', '\x2', '\x10', 'k', '\x3', '\x2', '\x2', '\x2', '\x12', 
		'n', '\x3', '\x2', '\x2', '\x2', '\x14', '~', '\x3', '\x2', '\x2', '\x2', 
		'\x16', '\x81', '\x3', '\x2', '\x2', '\x2', '\x18', '\x86', '\x3', '\x2', 
		'\x2', '\x2', '\x1A', '\x88', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x92', 
		'\x3', '\x2', '\x2', '\x2', '\x1E', '\x94', '\x3', '\x2', '\x2', '\x2', 
		' ', '\x9E', '\x3', '\x2', '\x2', '\x2', '\"', '\xA1', '\x3', '\x2', '\x2', 
		'\x2', '$', '\xA6', '\x3', '\x2', '\x2', '\x2', '&', '\xAC', '\x3', '\x2', 
		'\x2', '\x2', '(', '\xB7', '\x3', '\x2', '\x2', '\x2', '*', '\xBF', '\x3', 
		'\x2', '\x2', '\x2', ',', '\xC2', '\x3', '\x2', '\x2', '\x2', '.', '\xCA', 
		'\x3', '\x2', '\x2', '\x2', '\x30', '\xD4', '\x3', '\x2', '\x2', '\x2', 
		'\x32', '\xF5', '\x3', '\x2', '\x2', '\x2', '\x34', '\xF7', '\x3', '\x2', 
		'\x2', '\x2', '\x36', '\xFA', '\x3', '\x2', '\x2', '\x2', '\x38', '\xFC', 
		'\x3', '\x2', '\x2', '\x2', ':', '\xFE', '\x3', '\x2', '\x2', '\x2', '<', 
		'?', '\x5', '\x6', '\x4', '\x2', '=', '?', '\x5', '\x4', '\x3', '\x2', 
		'>', '<', '\x3', '\x2', '\x2', '\x2', '>', '=', '\x3', '\x2', '\x2', '\x2', 
		'?', '\x42', '\x3', '\x2', '\x2', '\x2', '@', '>', '\x3', '\x2', '\x2', 
		'\x2', '@', '\x41', '\x3', '\x2', '\x2', '\x2', '\x41', '\x43', '\x3', 
		'\x2', '\x2', '\x2', '\x42', '@', '\x3', '\x2', '\x2', '\x2', '\x43', 
		'\x44', '\a', '\x2', '\x2', '\x3', '\x44', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '\x45', '\x46', '\a', '\x35', '\x2', '\x2', '\x46', 'G', '\b', 
		'\x3', '\x1', '\x2', 'G', '\x5', '\x3', '\x2', '\x2', '\x2', 'H', 'I', 
		'\a', '\x16', '\x2', '\x2', 'I', 'J', '\a', '\x31', '\x2', '\x2', 'J', 
		'K', '\a', ')', '\x2', '\x2', 'K', 'L', '\x5', '\b', '\x5', '\x2', 'L', 
		'M', '\a', '*', '\x2', '\x2', 'M', '\a', '\x3', '\x2', '\x2', '\x2', 'N', 
		'P', '\x5', '\n', '\x6', '\x2', 'O', 'N', '\x3', '\x2', '\x2', '\x2', 
		'P', 'S', '\x3', '\x2', '\x2', '\x2', 'Q', 'O', '\x3', '\x2', '\x2', '\x2', 
		'Q', 'R', '\x3', '\x2', '\x2', '\x2', 'R', '\t', '\x3', '\x2', '\x2', 
		'\x2', 'S', 'Q', '\x3', '\x2', '\x2', '\x2', 'T', 'U', '\a', '\x17', '\x2', 
		'\x2', 'U', 'V', '\a', '\x31', '\x2', '\x2', 'V', 'W', '\a', ')', '\x2', 
		'\x2', 'W', 'X', '\x5', '\f', '\a', '\x2', 'X', 'Y', '\a', '*', '\x2', 
		'\x2', 'Y', '\v', '\x3', '\x2', '\x2', '\x2', 'Z', '_', '\x5', '\xE', 
		'\b', '\x2', '[', '_', '\x5', '\x1E', '\x10', '\x2', '\\', '_', '\x5', 
		'(', '\x15', '\x2', ']', '_', '\x5', '\n', '\x6', '\x2', '^', 'Z', '\x3', 
		'\x2', '\x2', '\x2', '^', '[', '\x3', '\x2', '\x2', '\x2', '^', '\\', 
		'\x3', '\x2', '\x2', '\x2', '^', ']', '\x3', '\x2', '\x2', '\x2', '_', 
		'\x62', '\x3', '\x2', '\x2', '\x2', '`', '^', '\x3', '\x2', '\x2', '\x2', 
		'`', '\x61', '\x3', '\x2', '\x2', '\x2', '\x61', '\r', '\x3', '\x2', '\x2', 
		'\x2', '\x62', '`', '\x3', '\x2', '\x2', '\x2', '\x63', '\x64', '\a', 
		'\x18', '\x2', '\x2', '\x64', '\x65', '\a', ')', '\x2', '\x2', '\x65', 
		'\x66', '\x5', '\x10', '\t', '\x2', '\x66', 'g', '\a', '*', '\x2', '\x2', 
		'g', '\xF', '\x3', '\x2', '\x2', '\x2', 'h', 'j', '\x5', '\x12', '\n', 
		'\x2', 'i', 'h', '\x3', '\x2', '\x2', '\x2', 'j', 'm', '\x3', '\x2', '\x2', 
		'\x2', 'k', 'i', '\x3', '\x2', '\x2', '\x2', 'k', 'l', '\x3', '\x2', '\x2', 
		'\x2', 'l', '\x11', '\x3', '\x2', '\x2', '\x2', 'm', 'k', '\x3', '\x2', 
		'\x2', '\x2', 'n', 'p', '\a', '\x31', '\x2', '\x2', 'o', 'q', '\a', '.', 
		'\x2', '\x2', 'p', 'o', '\x3', '\x2', '\x2', '\x2', 'p', 'q', '\x3', '\x2', 
		'\x2', '\x2', 'q', 'r', '\x3', '\x2', '\x2', '\x2', 'r', 'x', '\x5', '\x32', 
		'\x1A', '\x2', 's', 't', '\a', ')', '\x2', '\x2', 't', 'u', '\x5', '\x14', 
		'\v', '\x2', 'u', 'v', '\a', '*', '\x2', '\x2', 'v', 'y', '\x3', '\x2', 
		'\x2', '\x2', 'w', 'y', '\a', '%', '\x2', '\x2', 'x', 's', '\x3', '\x2', 
		'\x2', '\x2', 'x', 'w', '\x3', '\x2', '\x2', '\x2', 'y', '\x13', '\x3', 
		'\x2', '\x2', '\x2', 'z', '}', '\x5', '\x16', '\f', '\x2', '{', '}', '\x5', 
		'\x1A', '\xE', '\x2', '|', 'z', '\x3', '\x2', '\x2', '\x2', '|', '{', 
		'\x3', '\x2', '\x2', '\x2', '}', '\x80', '\x3', '\x2', '\x2', '\x2', '~', 
		'|', '\x3', '\x2', '\x2', '\x2', '~', '\x7F', '\x3', '\x2', '\x2', '\x2', 
		'\x7F', '\x15', '\x3', '\x2', '\x2', '\x2', '\x80', '~', '\x3', '\x2', 
		'\x2', '\x2', '\x81', '\x82', '\a', '\x1B', '\x2', '\x2', '\x82', '\x83', 
		'\a', ',', '\x2', '\x2', '\x83', '\x84', '\x5', '\x18', '\r', '\x2', '\x84', 
		'\x85', '\a', '%', '\x2', '\x2', '\x85', '\x17', '\x3', '\x2', '\x2', 
		'\x2', '\x86', '\x87', '\a', '\x5', '\x2', '\x2', '\x87', '\x19', '\x3', 
		'\x2', '\x2', '\x2', '\x88', '\x89', '\a', '\x1C', '\x2', '\x2', '\x89', 
		'\x8A', '\a', ',', '\x2', '\x2', '\x8A', '\x8B', '\x5', '\x1C', '\xF', 
		'\x2', '\x8B', '\x8C', '\a', '%', '\x2', '\x2', '\x8C', '\x1B', '\x3', 
		'\x2', '\x2', '\x2', '\x8D', '\x93', '\a', '\x3', '\x2', '\x2', '\x8E', 
		'\x93', '\a', '\x4', '\x2', '\x2', '\x8F', '\x90', '\a', '\x15', '\x2', 
		'\x2', '\x90', '\x91', '\a', '\'', '\x2', '\x2', '\x91', '\x93', '\a', 
		'(', '\x2', '\x2', '\x92', '\x8D', '\x3', '\x2', '\x2', '\x2', '\x92', 
		'\x8E', '\x3', '\x2', '\x2', '\x2', '\x92', '\x8F', '\x3', '\x2', '\x2', 
		'\x2', '\x93', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x94', '\x95', '\a', 
		'\x19', '\x2', '\x2', '\x95', '\x96', '\a', ')', '\x2', '\x2', '\x96', 
		'\x97', '\x5', ' ', '\x11', '\x2', '\x97', '\x98', '\a', '*', '\x2', '\x2', 
		'\x98', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9D', '\x5', '\"', 
		'\x12', '\x2', '\x9A', '\x9D', '\x5', '$', '\x13', '\x2', '\x9B', '\x9D', 
		'\x5', '&', '\x14', '\x2', '\x9C', '\x99', '\x3', '\x2', '\x2', '\x2', 
		'\x9C', '\x9A', '\x3', '\x2', '\x2', '\x2', '\x9C', '\x9B', '\x3', '\x2', 
		'\x2', '\x2', '\x9D', '\xA0', '\x3', '\x2', '\x2', '\x2', '\x9E', '\x9C', 
		'\x3', '\x2', '\x2', '\x2', '\x9E', '\x9F', '\x3', '\x2', '\x2', '\x2', 
		'\x9F', '!', '\x3', '\x2', '\x2', '\x2', '\xA0', '\x9E', '\x3', '\x2', 
		'\x2', '\x2', '\xA1', '\xA2', '\a', '\x1D', '\x2', '\x2', '\xA2', '\xA3', 
		'\a', ',', '\x2', '\x2', '\xA3', '\xA4', '\x5', '\x30', '\x19', '\x2', 
		'\xA4', '\xA5', '\a', '%', '\x2', '\x2', '\xA5', '#', '\x3', '\x2', '\x2', 
		'\x2', '\xA6', '\xA7', '\a', '\x1E', '\x2', '\x2', '\xA7', '\xA8', '\a', 
		'\'', '\x2', '\x2', '\xA8', '\xA9', '\x5', '\x30', '\x19', '\x2', '\xA9', 
		'\xAA', '\a', '(', '\x2', '\x2', '\xAA', '\xAB', '\a', '%', '\x2', '\x2', 
		'\xAB', '%', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAD', '\a', '\x1F', 
		'\x2', '\x2', '\xAD', '\xAE', '\a', '\'', '\x2', '\x2', '\xAE', '\xAF', 
		'\x5', '\x30', '\x19', '\x2', '\xAF', '\xB0', '\a', '(', '\x2', '\x2', 
		'\xB0', '\xB1', '\a', '\x30', '\x2', '\x2', '\xB1', '\xB2', '\x5', '.', 
		'\x18', '\x2', '\xB2', '\xB3', '\a', '\'', '\x2', '\x2', '\xB3', '\xB4', 
		'\x5', '\x30', '\x19', '\x2', '\xB4', '\xB5', '\a', '(', '\x2', '\x2', 
		'\xB5', '\xB6', '\a', '%', '\x2', '\x2', '\xB6', '\'', '\x3', '\x2', '\x2', 
		'\x2', '\xB7', '\xB8', '\a', '\x1A', '\x2', '\x2', '\xB8', '\xB9', '\a', 
		')', '\x2', '\x2', '\xB9', '\xBA', '\x5', '*', '\x16', '\x2', '\xBA', 
		'\xBB', '\a', '*', '\x2', '\x2', '\xBB', ')', '\x3', '\x2', '\x2', '\x2', 
		'\xBC', '\xBE', '\x5', ',', '\x17', '\x2', '\xBD', '\xBC', '\x3', '\x2', 
		'\x2', '\x2', '\xBE', '\xC1', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xBD', 
		'\x3', '\x2', '\x2', '\x2', '\xBF', '\xC0', '\x3', '\x2', '\x2', '\x2', 
		'\xC0', '+', '\x3', '\x2', '\x2', '\x2', '\xC1', '\xBF', '\x3', '\x2', 
		'\x2', '\x2', '\xC2', '\xC3', '\a', '\x31', '\x2', '\x2', '\xC3', '\xC4', 
		'\a', '\'', '\x2', '\x2', '\xC4', '\xC5', '\x5', '\x30', '\x19', '\x2', 
		'\xC5', '\xC6', '\a', '(', '\x2', '\x2', '\xC6', '\xC7', '\a', '%', '\x2', 
		'\x2', '\xC7', '-', '\x3', '\x2', '\x2', '\x2', '\xC8', '\xC9', '\a', 
		'\x31', '\x2', '\x2', '\xC9', '\xCB', '\a', '/', '\x2', '\x2', '\xCA', 
		'\xC8', '\x3', '\x2', '\x2', '\x2', '\xCA', '\xCB', '\x3', '\x2', '\x2', 
		'\x2', '\xCB', '\xCC', '\x3', '\x2', '\x2', '\x2', '\xCC', '\xD1', '\a', 
		'\x31', '\x2', '\x2', '\xCD', '\xCE', '\a', '&', '\x2', '\x2', '\xCE', 
		'\xD0', '\a', '\x31', '\x2', '\x2', '\xCF', '\xCD', '\x3', '\x2', '\x2', 
		'\x2', '\xD0', '\xD3', '\x3', '\x2', '\x2', '\x2', '\xD1', '\xCF', '\x3', 
		'\x2', '\x2', '\x2', '\xD1', '\xD2', '\x3', '\x2', '\x2', '\x2', '\xD2', 
		'/', '\x3', '\x2', '\x2', '\x2', '\xD3', '\xD1', '\x3', '\x2', '\x2', 
		'\x2', '\xD4', '\xD9', '\a', '\x31', '\x2', '\x2', '\xD5', '\xD6', '\a', 
		'+', '\x2', '\x2', '\xD6', '\xD8', '\a', '\x31', '\x2', '\x2', '\xD7', 
		'\xD5', '\x3', '\x2', '\x2', '\x2', '\xD8', '\xDB', '\x3', '\x2', '\x2', 
		'\x2', '\xD9', '\xD7', '\x3', '\x2', '\x2', '\x2', '\xD9', '\xDA', '\x3', 
		'\x2', '\x2', '\x2', '\xDA', '\x31', '\x3', '\x2', '\x2', '\x2', '\xDB', 
		'\xD9', '\x3', '\x2', '\x2', '\x2', '\xDC', '\xF6', '\a', '\v', '\x2', 
		'\x2', '\xDD', '\xF6', '\a', '\f', '\x2', '\x2', '\xDE', '\xE0', '\a', 
		'\r', '\x2', '\x2', '\xDF', '\xE1', '\x5', '\x34', '\x1B', '\x2', '\xE0', 
		'\xDF', '\x3', '\x2', '\x2', '\x2', '\xE0', '\xE1', '\x3', '\x2', '\x2', 
		'\x2', '\xE1', '\xF6', '\x3', '\x2', '\x2', '\x2', '\xE2', '\xF6', '\a', 
		'\xE', '\x2', '\x2', '\xE3', '\xE4', '\a', '\xF', '\x2', '\x2', '\xE4', 
		'\xE5', '\a', '\'', '\x2', '\x2', '\xE5', '\xE6', '\x5', '\x36', '\x1C', 
		'\x2', '\xE6', '\xE7', '\a', '(', '\x2', '\x2', '\xE7', '\xF6', '\x3', 
		'\x2', '\x2', '\x2', '\xE8', '\xF6', '\a', '\x10', '\x2', '\x2', '\xE9', 
		'\xF6', '\a', '\x11', '\x2', '\x2', '\xEA', '\xEB', '\a', '\x12', '\x2', 
		'\x2', '\xEB', '\xEC', '\a', '\'', '\x2', '\x2', '\xEC', '\xED', '\x5', 
		'\x38', '\x1D', '\x2', '\xED', '\xEE', '\a', '(', '\x2', '\x2', '\xEE', 
		'\xF6', '\x3', '\x2', '\x2', '\x2', '\xEF', '\xF0', '\a', '\x13', '\x2', 
		'\x2', '\xF0', '\xF1', '\a', '\'', '\x2', '\x2', '\xF1', '\xF2', '\x5', 
		':', '\x1E', '\x2', '\xF2', '\xF3', '\a', '(', '\x2', '\x2', '\xF3', '\xF6', 
		'\x3', '\x2', '\x2', '\x2', '\xF4', '\xF6', '\a', '\x14', '\x2', '\x2', 
		'\xF5', '\xDC', '\x3', '\x2', '\x2', '\x2', '\xF5', '\xDD', '\x3', '\x2', 
		'\x2', '\x2', '\xF5', '\xDE', '\x3', '\x2', '\x2', '\x2', '\xF5', '\xE2', 
		'\x3', '\x2', '\x2', '\x2', '\xF5', '\xE3', '\x3', '\x2', '\x2', '\x2', 
		'\xF5', '\xE8', '\x3', '\x2', '\x2', '\x2', '\xF5', '\xE9', '\x3', '\x2', 
		'\x2', '\x2', '\xF5', '\xEA', '\x3', '\x2', '\x2', '\x2', '\xF5', '\xEF', 
		'\x3', '\x2', '\x2', '\x2', '\xF5', '\xF4', '\x3', '\x2', '\x2', '\x2', 
		'\xF6', '\x33', '\x3', '\x2', '\x2', '\x2', '\xF7', '\xF8', '\a', ' ', 
		'\x2', '\x2', '\xF8', '\xF9', '\a', '!', '\x2', '\x2', '\xF9', '\x35', 
		'\x3', '\x2', '\x2', '\x2', '\xFA', '\xFB', '\t', '\x2', '\x2', '\x2', 
		'\xFB', '\x37', '\x3', '\x2', '\x2', '\x2', '\xFC', '\xFD', '\t', '\x2', 
		'\x2', '\x2', '\xFD', '\x39', '\x3', '\x2', '\x2', '\x2', '\xFE', '\xFF', 
		'\a', '\a', '\x2', '\x2', '\xFF', ';', '\x3', '\x2', '\x2', '\x2', '\x15', 
		'>', '@', 'Q', '^', '`', 'k', 'p', 'x', '|', '~', '\x92', '\x9C', '\x9E', 
		'\xBF', '\xCA', '\xD1', '\xD9', '\xE0', '\xF5',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
