//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from KayleeParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class KayleeParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		NUMERIC_LITERAL=1, STRING_LITERAL=2, BOOLEAN=3, INTEGER=4, UNSIGNED_INTEGER=5, 
		FLOAT=6, UNSIGNED_FLOAT=7, HEX_NUMBER=8, DTYPE_BIT=9, DTYPE_TINYINT=10, 
		DTYPE_INT=11, DTYPE_CHAR=12, DTYPE_TEXT=13, DTYPE_GUID=14, DTYPE_DATE=15, 
		DTYPE_ROWVERSION=16, FIELD_PARAMETER_DEFAULT_FUNCTION=17, SCHEMA=18, ENTITY=19, 
		FIELDS=20, KEYS=21, MUTATIONS=22, DEFAULT=23, PRIMARY=24, REFERENCE=25, 
		AUTO=26, INCREMENT=27, MAX=28, TRUE=29, FALSE=30, SCOL=31, DOT=32, OPEN_PAR=33, 
		CLOSE_PAR=34, OPEN_BLOCK=35, CLOSE_BLOCK=36, COMMA=37, ASSIGN=38, MINUS=39, 
		QUESTION_MARK=40, SCHEMA_ACCESSOR=41, ARROW=42, IDENTIFIER=43, SINGLE_LINE_COMMENT=44, 
		MULTI_LINE_COMMENT=45, WHITESPACE=46, UNEXPECTED_CHAR=47;
	public const int
		RULE_parse = 0, RULE_error = 1, RULE_schema = 2, RULE_schemaBody = 3, 
		RULE_entity = 4, RULE_entityBody = 5, RULE_fields = 6, RULE_fieldsBody = 7, 
		RULE_field = 8, RULE_fieldBody = 9, RULE_fieldParameterDefault = 10, RULE_fieldParameterDefaultValue = 11, 
		RULE_entityKeys = 12, RULE_entityKeysBody = 13, RULE_entityKeyPrimary = 14, 
		RULE_entityKeyReference = 15, RULE_mutations = 16, RULE_mutationsBody = 17, 
		RULE_mutation = 18, RULE_qualified = 19, RULE_identifierList = 20, RULE_dtype = 21;
	public static readonly string[] ruleNames = {
		"parse", "error", "schema", "schemaBody", "entity", "entityBody", "fields", 
		"fieldsBody", "field", "fieldBody", "fieldParameterDefault", "fieldParameterDefaultValue", 
		"entityKeys", "entityKeysBody", "entityKeyPrimary", "entityKeyReference", 
		"mutations", "mutationsBody", "mutation", "qualified", "identifierList", 
		"dtype"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, null, null, null, "'BIT'", "'TINYINT'", 
		"'INT'", "'CHAR'", "'TEXT'", "'GUID'", "'DATE'", "'ROWVERSION'", null, 
		"'schema'", "'entity'", "'fields'", "'keys'", "'mutations'", "'default'", 
		"'primary'", "'reference'", "'AUTO'", "'INCREMENT'", "'MAX'", "'true'", 
		"'false'", "';'", "'.'", "'('", "')'", "'{'", "'}'", "','", "'='", "'-'", 
		"'?'", "'::'", "'=>'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "NUMERIC_LITERAL", "STRING_LITERAL", "BOOLEAN", "INTEGER", "UNSIGNED_INTEGER", 
		"FLOAT", "UNSIGNED_FLOAT", "HEX_NUMBER", "DTYPE_BIT", "DTYPE_TINYINT", 
		"DTYPE_INT", "DTYPE_CHAR", "DTYPE_TEXT", "DTYPE_GUID", "DTYPE_DATE", "DTYPE_ROWVERSION", 
		"FIELD_PARAMETER_DEFAULT_FUNCTION", "SCHEMA", "ENTITY", "FIELDS", "KEYS", 
		"MUTATIONS", "DEFAULT", "PRIMARY", "REFERENCE", "AUTO", "INCREMENT", "MAX", 
		"TRUE", "FALSE", "SCOL", "DOT", "OPEN_PAR", "CLOSE_PAR", "OPEN_BLOCK", 
		"CLOSE_BLOCK", "COMMA", "ASSIGN", "MINUS", "QUESTION_MARK", "SCHEMA_ACCESSOR", 
		"ARROW", "IDENTIFIER", "SINGLE_LINE_COMMENT", "MULTI_LINE_COMMENT", "WHITESPACE", 
		"UNEXPECTED_CHAR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "KayleeParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static KayleeParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public KayleeParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public KayleeParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ParseContext : ParserRuleContext {
		public ITerminalNode Eof() { return GetToken(KayleeParser.Eof, 0); }
		public SchemaContext[] schema() {
			return GetRuleContexts<SchemaContext>();
		}
		public SchemaContext schema(int i) {
			return GetRuleContext<SchemaContext>(i);
		}
		public ErrorContext[] error() {
			return GetRuleContexts<ErrorContext>();
		}
		public ErrorContext error(int i) {
			return GetRuleContext<ErrorContext>(i);
		}
		public ParseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parse; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterParse(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitParse(this);
		}
	}

	[RuleVersion(0)]
	public ParseContext parse() {
		ParseContext _localctx = new ParseContext(Context, State);
		EnterRule(_localctx, 0, RULE_parse);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 48;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==SCHEMA || _la==UNEXPECTED_CHAR) {
				{
				State = 46;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case SCHEMA:
					{
					State = 44; schema();
					}
					break;
				case UNEXPECTED_CHAR:
					{
					State = 45; error();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 50;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 51; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ErrorContext : ParserRuleContext {
		public IToken _UNEXPECTED_CHAR;
		public ITerminalNode UNEXPECTED_CHAR() { return GetToken(KayleeParser.UNEXPECTED_CHAR, 0); }
		public ErrorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_error; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterError(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitError(this);
		}
	}

	[RuleVersion(0)]
	public ErrorContext error() {
		ErrorContext _localctx = new ErrorContext(Context, State);
		EnterRule(_localctx, 2, RULE_error);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 53; _localctx._UNEXPECTED_CHAR = Match(UNEXPECTED_CHAR);

				throw new FormatException("UNEXPECTED_CHAR=" + (_localctx._UNEXPECTED_CHAR!=null?_localctx._UNEXPECTED_CHAR.Text:null));

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SchemaContext : ParserRuleContext {
		public ITerminalNode SCHEMA() { return GetToken(KayleeParser.SCHEMA, 0); }
		public ITerminalNode IDENTIFIER() { return GetToken(KayleeParser.IDENTIFIER, 0); }
		public ITerminalNode OPEN_BLOCK() { return GetToken(KayleeParser.OPEN_BLOCK, 0); }
		public SchemaBodyContext schemaBody() {
			return GetRuleContext<SchemaBodyContext>(0);
		}
		public ITerminalNode CLOSE_BLOCK() { return GetToken(KayleeParser.CLOSE_BLOCK, 0); }
		public SchemaContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_schema; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterSchema(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitSchema(this);
		}
	}

	[RuleVersion(0)]
	public SchemaContext schema() {
		SchemaContext _localctx = new SchemaContext(Context, State);
		EnterRule(_localctx, 4, RULE_schema);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 56; Match(SCHEMA);
			State = 57; Match(IDENTIFIER);
			State = 58; Match(OPEN_BLOCK);
			State = 59; schemaBody();
			State = 60; Match(CLOSE_BLOCK);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SchemaBodyContext : ParserRuleContext {
		public EntityContext[] entity() {
			return GetRuleContexts<EntityContext>();
		}
		public EntityContext entity(int i) {
			return GetRuleContext<EntityContext>(i);
		}
		public SchemaBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_schemaBody; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterSchemaBody(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitSchemaBody(this);
		}
	}

	[RuleVersion(0)]
	public SchemaBodyContext schemaBody() {
		SchemaBodyContext _localctx = new SchemaBodyContext(Context, State);
		EnterRule(_localctx, 6, RULE_schemaBody);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 65;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==ENTITY) {
				{
				{
				State = 62; entity();
				}
				}
				State = 67;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EntityContext : ParserRuleContext {
		public ITerminalNode ENTITY() { return GetToken(KayleeParser.ENTITY, 0); }
		public ITerminalNode IDENTIFIER() { return GetToken(KayleeParser.IDENTIFIER, 0); }
		public ITerminalNode OPEN_BLOCK() { return GetToken(KayleeParser.OPEN_BLOCK, 0); }
		public EntityBodyContext entityBody() {
			return GetRuleContext<EntityBodyContext>(0);
		}
		public ITerminalNode CLOSE_BLOCK() { return GetToken(KayleeParser.CLOSE_BLOCK, 0); }
		public EntityContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_entity; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterEntity(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitEntity(this);
		}
	}

	[RuleVersion(0)]
	public EntityContext entity() {
		EntityContext _localctx = new EntityContext(Context, State);
		EnterRule(_localctx, 8, RULE_entity);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 68; Match(ENTITY);
			State = 69; Match(IDENTIFIER);
			State = 70; Match(OPEN_BLOCK);
			State = 71; entityBody();
			State = 72; Match(CLOSE_BLOCK);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EntityBodyContext : ParserRuleContext {
		public FieldsContext[] fields() {
			return GetRuleContexts<FieldsContext>();
		}
		public FieldsContext fields(int i) {
			return GetRuleContext<FieldsContext>(i);
		}
		public EntityKeysContext[] entityKeys() {
			return GetRuleContexts<EntityKeysContext>();
		}
		public EntityKeysContext entityKeys(int i) {
			return GetRuleContext<EntityKeysContext>(i);
		}
		public MutationsContext[] mutations() {
			return GetRuleContexts<MutationsContext>();
		}
		public MutationsContext mutations(int i) {
			return GetRuleContext<MutationsContext>(i);
		}
		public EntityContext[] entity() {
			return GetRuleContexts<EntityContext>();
		}
		public EntityContext entity(int i) {
			return GetRuleContext<EntityContext>(i);
		}
		public EntityBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_entityBody; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterEntityBody(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitEntityBody(this);
		}
	}

	[RuleVersion(0)]
	public EntityBodyContext entityBody() {
		EntityBodyContext _localctx = new EntityBodyContext(Context, State);
		EnterRule(_localctx, 10, RULE_entityBody);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 80;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << ENTITY) | (1L << FIELDS) | (1L << KEYS) | (1L << MUTATIONS))) != 0)) {
				{
				State = 78;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case FIELDS:
					{
					State = 74; fields();
					}
					break;
				case KEYS:
					{
					State = 75; entityKeys();
					}
					break;
				case MUTATIONS:
					{
					State = 76; mutations();
					}
					break;
				case ENTITY:
					{
					State = 77; entity();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 82;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FieldsContext : ParserRuleContext {
		public ITerminalNode FIELDS() { return GetToken(KayleeParser.FIELDS, 0); }
		public ITerminalNode OPEN_BLOCK() { return GetToken(KayleeParser.OPEN_BLOCK, 0); }
		public FieldsBodyContext fieldsBody() {
			return GetRuleContext<FieldsBodyContext>(0);
		}
		public ITerminalNode CLOSE_BLOCK() { return GetToken(KayleeParser.CLOSE_BLOCK, 0); }
		public FieldsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fields; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterFields(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitFields(this);
		}
	}

	[RuleVersion(0)]
	public FieldsContext fields() {
		FieldsContext _localctx = new FieldsContext(Context, State);
		EnterRule(_localctx, 12, RULE_fields);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 83; Match(FIELDS);
			State = 84; Match(OPEN_BLOCK);
			State = 85; fieldsBody();
			State = 86; Match(CLOSE_BLOCK);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FieldsBodyContext : ParserRuleContext {
		public FieldContext[] field() {
			return GetRuleContexts<FieldContext>();
		}
		public FieldContext field(int i) {
			return GetRuleContext<FieldContext>(i);
		}
		public FieldsBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fieldsBody; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterFieldsBody(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitFieldsBody(this);
		}
	}

	[RuleVersion(0)]
	public FieldsBodyContext fieldsBody() {
		FieldsBodyContext _localctx = new FieldsBodyContext(Context, State);
		EnterRule(_localctx, 14, RULE_fieldsBody);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 91;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==IDENTIFIER) {
				{
				{
				State = 88; field();
				}
				}
				State = 93;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FieldContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(KayleeParser.IDENTIFIER, 0); }
		public DtypeContext dtype() {
			return GetRuleContext<DtypeContext>(0);
		}
		public ITerminalNode OPEN_BLOCK() { return GetToken(KayleeParser.OPEN_BLOCK, 0); }
		public FieldBodyContext fieldBody() {
			return GetRuleContext<FieldBodyContext>(0);
		}
		public ITerminalNode CLOSE_BLOCK() { return GetToken(KayleeParser.CLOSE_BLOCK, 0); }
		public ITerminalNode SCOL() { return GetToken(KayleeParser.SCOL, 0); }
		public ITerminalNode QUESTION_MARK() { return GetToken(KayleeParser.QUESTION_MARK, 0); }
		public FieldContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_field; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterField(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitField(this);
		}
	}

	[RuleVersion(0)]
	public FieldContext field() {
		FieldContext _localctx = new FieldContext(Context, State);
		EnterRule(_localctx, 16, RULE_field);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 94; Match(IDENTIFIER);
			State = 96;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==QUESTION_MARK) {
				{
				State = 95; Match(QUESTION_MARK);
				}
			}

			State = 98; dtype();
			State = 104;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case OPEN_BLOCK:
				{
				State = 99; Match(OPEN_BLOCK);
				State = 100; fieldBody();
				State = 101; Match(CLOSE_BLOCK);
				}
				break;
			case SCOL:
				{
				State = 103; Match(SCOL);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FieldBodyContext : ParserRuleContext {
		public FieldParameterDefaultContext[] fieldParameterDefault() {
			return GetRuleContexts<FieldParameterDefaultContext>();
		}
		public FieldParameterDefaultContext fieldParameterDefault(int i) {
			return GetRuleContext<FieldParameterDefaultContext>(i);
		}
		public FieldBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fieldBody; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterFieldBody(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitFieldBody(this);
		}
	}

	[RuleVersion(0)]
	public FieldBodyContext fieldBody() {
		FieldBodyContext _localctx = new FieldBodyContext(Context, State);
		EnterRule(_localctx, 18, RULE_fieldBody);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 109;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==DEFAULT) {
				{
				{
				State = 106; fieldParameterDefault();
				}
				}
				State = 111;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FieldParameterDefaultContext : ParserRuleContext {
		public ITerminalNode DEFAULT() { return GetToken(KayleeParser.DEFAULT, 0); }
		public ITerminalNode ASSIGN() { return GetToken(KayleeParser.ASSIGN, 0); }
		public FieldParameterDefaultValueContext fieldParameterDefaultValue() {
			return GetRuleContext<FieldParameterDefaultValueContext>(0);
		}
		public ITerminalNode SCOL() { return GetToken(KayleeParser.SCOL, 0); }
		public FieldParameterDefaultContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fieldParameterDefault; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterFieldParameterDefault(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitFieldParameterDefault(this);
		}
	}

	[RuleVersion(0)]
	public FieldParameterDefaultContext fieldParameterDefault() {
		FieldParameterDefaultContext _localctx = new FieldParameterDefaultContext(Context, State);
		EnterRule(_localctx, 20, RULE_fieldParameterDefault);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 112; Match(DEFAULT);
			State = 113; Match(ASSIGN);
			State = 114; fieldParameterDefaultValue();
			State = 115; Match(SCOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FieldParameterDefaultValueContext : ParserRuleContext {
		public ITerminalNode NUMERIC_LITERAL() { return GetToken(KayleeParser.NUMERIC_LITERAL, 0); }
		public ITerminalNode STRING_LITERAL() { return GetToken(KayleeParser.STRING_LITERAL, 0); }
		public ITerminalNode FIELD_PARAMETER_DEFAULT_FUNCTION() { return GetToken(KayleeParser.FIELD_PARAMETER_DEFAULT_FUNCTION, 0); }
		public ITerminalNode OPEN_PAR() { return GetToken(KayleeParser.OPEN_PAR, 0); }
		public ITerminalNode CLOSE_PAR() { return GetToken(KayleeParser.CLOSE_PAR, 0); }
		public FieldParameterDefaultValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fieldParameterDefaultValue; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterFieldParameterDefaultValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitFieldParameterDefaultValue(this);
		}
	}

	[RuleVersion(0)]
	public FieldParameterDefaultValueContext fieldParameterDefaultValue() {
		FieldParameterDefaultValueContext _localctx = new FieldParameterDefaultValueContext(Context, State);
		EnterRule(_localctx, 22, RULE_fieldParameterDefaultValue);
		try {
			State = 122;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NUMERIC_LITERAL:
				EnterOuterAlt(_localctx, 1);
				{
				State = 117; Match(NUMERIC_LITERAL);
				}
				break;
			case STRING_LITERAL:
				EnterOuterAlt(_localctx, 2);
				{
				State = 118; Match(STRING_LITERAL);
				}
				break;
			case FIELD_PARAMETER_DEFAULT_FUNCTION:
				EnterOuterAlt(_localctx, 3);
				{
				State = 119; Match(FIELD_PARAMETER_DEFAULT_FUNCTION);
				State = 120; Match(OPEN_PAR);
				State = 121; Match(CLOSE_PAR);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EntityKeysContext : ParserRuleContext {
		public ITerminalNode KEYS() { return GetToken(KayleeParser.KEYS, 0); }
		public ITerminalNode OPEN_BLOCK() { return GetToken(KayleeParser.OPEN_BLOCK, 0); }
		public EntityKeysBodyContext entityKeysBody() {
			return GetRuleContext<EntityKeysBodyContext>(0);
		}
		public ITerminalNode CLOSE_BLOCK() { return GetToken(KayleeParser.CLOSE_BLOCK, 0); }
		public EntityKeysContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_entityKeys; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterEntityKeys(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitEntityKeys(this);
		}
	}

	[RuleVersion(0)]
	public EntityKeysContext entityKeys() {
		EntityKeysContext _localctx = new EntityKeysContext(Context, State);
		EnterRule(_localctx, 24, RULE_entityKeys);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 124; Match(KEYS);
			State = 125; Match(OPEN_BLOCK);
			State = 126; entityKeysBody();
			State = 127; Match(CLOSE_BLOCK);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EntityKeysBodyContext : ParserRuleContext {
		public EntityKeyPrimaryContext[] entityKeyPrimary() {
			return GetRuleContexts<EntityKeyPrimaryContext>();
		}
		public EntityKeyPrimaryContext entityKeyPrimary(int i) {
			return GetRuleContext<EntityKeyPrimaryContext>(i);
		}
		public EntityKeyReferenceContext[] entityKeyReference() {
			return GetRuleContexts<EntityKeyReferenceContext>();
		}
		public EntityKeyReferenceContext entityKeyReference(int i) {
			return GetRuleContext<EntityKeyReferenceContext>(i);
		}
		public EntityKeysBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_entityKeysBody; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterEntityKeysBody(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitEntityKeysBody(this);
		}
	}

	[RuleVersion(0)]
	public EntityKeysBodyContext entityKeysBody() {
		EntityKeysBodyContext _localctx = new EntityKeysBodyContext(Context, State);
		EnterRule(_localctx, 26, RULE_entityKeysBody);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 133;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==PRIMARY || _la==REFERENCE) {
				{
				State = 131;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case PRIMARY:
					{
					State = 129; entityKeyPrimary();
					}
					break;
				case REFERENCE:
					{
					State = 130; entityKeyReference();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 135;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EntityKeyPrimaryContext : ParserRuleContext {
		public ITerminalNode PRIMARY() { return GetToken(KayleeParser.PRIMARY, 0); }
		public ITerminalNode ASSIGN() { return GetToken(KayleeParser.ASSIGN, 0); }
		public IdentifierListContext identifierList() {
			return GetRuleContext<IdentifierListContext>(0);
		}
		public ITerminalNode SCOL() { return GetToken(KayleeParser.SCOL, 0); }
		public EntityKeyPrimaryContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_entityKeyPrimary; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterEntityKeyPrimary(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitEntityKeyPrimary(this);
		}
	}

	[RuleVersion(0)]
	public EntityKeyPrimaryContext entityKeyPrimary() {
		EntityKeyPrimaryContext _localctx = new EntityKeyPrimaryContext(Context, State);
		EnterRule(_localctx, 28, RULE_entityKeyPrimary);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 136; Match(PRIMARY);
			State = 137; Match(ASSIGN);
			State = 138; identifierList();
			State = 139; Match(SCOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EntityKeyReferenceContext : ParserRuleContext {
		public ITerminalNode REFERENCE() { return GetToken(KayleeParser.REFERENCE, 0); }
		public ITerminalNode[] OPEN_PAR() { return GetTokens(KayleeParser.OPEN_PAR); }
		public ITerminalNode OPEN_PAR(int i) {
			return GetToken(KayleeParser.OPEN_PAR, i);
		}
		public IdentifierListContext[] identifierList() {
			return GetRuleContexts<IdentifierListContext>();
		}
		public IdentifierListContext identifierList(int i) {
			return GetRuleContext<IdentifierListContext>(i);
		}
		public ITerminalNode[] CLOSE_PAR() { return GetTokens(KayleeParser.CLOSE_PAR); }
		public ITerminalNode CLOSE_PAR(int i) {
			return GetToken(KayleeParser.CLOSE_PAR, i);
		}
		public ITerminalNode ARROW() { return GetToken(KayleeParser.ARROW, 0); }
		public QualifiedContext qualified() {
			return GetRuleContext<QualifiedContext>(0);
		}
		public ITerminalNode SCOL() { return GetToken(KayleeParser.SCOL, 0); }
		public EntityKeyReferenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_entityKeyReference; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterEntityKeyReference(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitEntityKeyReference(this);
		}
	}

	[RuleVersion(0)]
	public EntityKeyReferenceContext entityKeyReference() {
		EntityKeyReferenceContext _localctx = new EntityKeyReferenceContext(Context, State);
		EnterRule(_localctx, 30, RULE_entityKeyReference);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 141; Match(REFERENCE);
			State = 142; Match(OPEN_PAR);
			State = 143; identifierList();
			State = 144; Match(CLOSE_PAR);
			State = 145; Match(ARROW);
			State = 146; qualified();
			State = 147; Match(OPEN_PAR);
			State = 148; identifierList();
			State = 149; Match(CLOSE_PAR);
			State = 150; Match(SCOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MutationsContext : ParserRuleContext {
		public ITerminalNode MUTATIONS() { return GetToken(KayleeParser.MUTATIONS, 0); }
		public ITerminalNode OPEN_BLOCK() { return GetToken(KayleeParser.OPEN_BLOCK, 0); }
		public MutationsBodyContext mutationsBody() {
			return GetRuleContext<MutationsBodyContext>(0);
		}
		public ITerminalNode CLOSE_BLOCK() { return GetToken(KayleeParser.CLOSE_BLOCK, 0); }
		public MutationsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mutations; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterMutations(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitMutations(this);
		}
	}

	[RuleVersion(0)]
	public MutationsContext mutations() {
		MutationsContext _localctx = new MutationsContext(Context, State);
		EnterRule(_localctx, 32, RULE_mutations);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 152; Match(MUTATIONS);
			State = 153; Match(OPEN_BLOCK);
			State = 154; mutationsBody();
			State = 155; Match(CLOSE_BLOCK);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MutationsBodyContext : ParserRuleContext {
		public MutationContext[] mutation() {
			return GetRuleContexts<MutationContext>();
		}
		public MutationContext mutation(int i) {
			return GetRuleContext<MutationContext>(i);
		}
		public MutationsBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mutationsBody; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterMutationsBody(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitMutationsBody(this);
		}
	}

	[RuleVersion(0)]
	public MutationsBodyContext mutationsBody() {
		MutationsBodyContext _localctx = new MutationsBodyContext(Context, State);
		EnterRule(_localctx, 34, RULE_mutationsBody);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 160;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==IDENTIFIER) {
				{
				{
				State = 157; mutation();
				}
				}
				State = 162;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MutationContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(KayleeParser.IDENTIFIER, 0); }
		public ITerminalNode OPEN_PAR() { return GetToken(KayleeParser.OPEN_PAR, 0); }
		public IdentifierListContext identifierList() {
			return GetRuleContext<IdentifierListContext>(0);
		}
		public ITerminalNode CLOSE_PAR() { return GetToken(KayleeParser.CLOSE_PAR, 0); }
		public ITerminalNode SCOL() { return GetToken(KayleeParser.SCOL, 0); }
		public MutationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mutation; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterMutation(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitMutation(this);
		}
	}

	[RuleVersion(0)]
	public MutationContext mutation() {
		MutationContext _localctx = new MutationContext(Context, State);
		EnterRule(_localctx, 36, RULE_mutation);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 163; Match(IDENTIFIER);
			State = 164; Match(OPEN_PAR);
			State = 165; identifierList();
			State = 166; Match(CLOSE_PAR);
			State = 167; Match(SCOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class QualifiedContext : ParserRuleContext {
		public ITerminalNode[] IDENTIFIER() { return GetTokens(KayleeParser.IDENTIFIER); }
		public ITerminalNode IDENTIFIER(int i) {
			return GetToken(KayleeParser.IDENTIFIER, i);
		}
		public ITerminalNode SCHEMA_ACCESSOR() { return GetToken(KayleeParser.SCHEMA_ACCESSOR, 0); }
		public ITerminalNode[] DOT() { return GetTokens(KayleeParser.DOT); }
		public ITerminalNode DOT(int i) {
			return GetToken(KayleeParser.DOT, i);
		}
		public QualifiedContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_qualified; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterQualified(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitQualified(this);
		}
	}

	[RuleVersion(0)]
	public QualifiedContext qualified() {
		QualifiedContext _localctx = new QualifiedContext(Context, State);
		EnterRule(_localctx, 38, RULE_qualified);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 171;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
			case 1:
				{
				State = 169; Match(IDENTIFIER);
				State = 170; Match(SCHEMA_ACCESSOR);
				}
				break;
			}
			State = 173; Match(IDENTIFIER);
			State = 178;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==DOT) {
				{
				{
				State = 174; Match(DOT);
				State = 175; Match(IDENTIFIER);
				}
				}
				State = 180;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdentifierListContext : ParserRuleContext {
		public ITerminalNode[] IDENTIFIER() { return GetTokens(KayleeParser.IDENTIFIER); }
		public ITerminalNode IDENTIFIER(int i) {
			return GetToken(KayleeParser.IDENTIFIER, i);
		}
		public ITerminalNode[] COMMA() { return GetTokens(KayleeParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(KayleeParser.COMMA, i);
		}
		public IdentifierListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_identifierList; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterIdentifierList(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitIdentifierList(this);
		}
	}

	[RuleVersion(0)]
	public IdentifierListContext identifierList() {
		IdentifierListContext _localctx = new IdentifierListContext(Context, State);
		EnterRule(_localctx, 40, RULE_identifierList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 181; Match(IDENTIFIER);
			State = 186;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 182; Match(COMMA);
				State = 183; Match(IDENTIFIER);
				}
				}
				State = 188;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DtypeContext : ParserRuleContext {
		public ITerminalNode DTYPE_BIT() { return GetToken(KayleeParser.DTYPE_BIT, 0); }
		public ITerminalNode DTYPE_TINYINT() { return GetToken(KayleeParser.DTYPE_TINYINT, 0); }
		public ITerminalNode DTYPE_INT() { return GetToken(KayleeParser.DTYPE_INT, 0); }
		public ITerminalNode AUTO() { return GetToken(KayleeParser.AUTO, 0); }
		public ITerminalNode INCREMENT() { return GetToken(KayleeParser.INCREMENT, 0); }
		public ITerminalNode DTYPE_CHAR() { return GetToken(KayleeParser.DTYPE_CHAR, 0); }
		public ITerminalNode DTYPE_TEXT() { return GetToken(KayleeParser.DTYPE_TEXT, 0); }
		public ITerminalNode OPEN_PAR() { return GetToken(KayleeParser.OPEN_PAR, 0); }
		public ITerminalNode CLOSE_PAR() { return GetToken(KayleeParser.CLOSE_PAR, 0); }
		public ITerminalNode UNSIGNED_INTEGER() { return GetToken(KayleeParser.UNSIGNED_INTEGER, 0); }
		public ITerminalNode MAX() { return GetToken(KayleeParser.MAX, 0); }
		public ITerminalNode DTYPE_GUID() { return GetToken(KayleeParser.DTYPE_GUID, 0); }
		public ITerminalNode DTYPE_DATE() { return GetToken(KayleeParser.DTYPE_DATE, 0); }
		public ITerminalNode DTYPE_ROWVERSION() { return GetToken(KayleeParser.DTYPE_ROWVERSION, 0); }
		public DtypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dtype; } }
		public override void EnterRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.EnterDtype(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IKayleeParserListener typedListener = listener as IKayleeParserListener;
			if (typedListener != null) typedListener.ExitDtype(this);
		}
	}

	[RuleVersion(0)]
	public DtypeContext dtype() {
		DtypeContext _localctx = new DtypeContext(Context, State);
		EnterRule(_localctx, 42, RULE_dtype);
		int _la;
		try {
			State = 204;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case DTYPE_BIT:
				EnterOuterAlt(_localctx, 1);
				{
				State = 189; Match(DTYPE_BIT);
				}
				break;
			case DTYPE_TINYINT:
				EnterOuterAlt(_localctx, 2);
				{
				State = 190; Match(DTYPE_TINYINT);
				}
				break;
			case DTYPE_INT:
				EnterOuterAlt(_localctx, 3);
				{
				State = 191; Match(DTYPE_INT);
				State = 194;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==AUTO) {
					{
					State = 192; Match(AUTO);
					State = 193; Match(INCREMENT);
					}
				}

				}
				break;
			case DTYPE_CHAR:
				EnterOuterAlt(_localctx, 4);
				{
				State = 196; Match(DTYPE_CHAR);
				}
				break;
			case DTYPE_TEXT:
				EnterOuterAlt(_localctx, 5);
				{
				State = 197; Match(DTYPE_TEXT);
				State = 198; Match(OPEN_PAR);
				State = 199;
				_la = TokenStream.LA(1);
				if ( !(_la==UNSIGNED_INTEGER || _la==MAX) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 200; Match(CLOSE_PAR);
				}
				break;
			case DTYPE_GUID:
				EnterOuterAlt(_localctx, 6);
				{
				State = 201; Match(DTYPE_GUID);
				}
				break;
			case DTYPE_DATE:
				EnterOuterAlt(_localctx, 7);
				{
				State = 202; Match(DTYPE_DATE);
				}
				break;
			case DTYPE_ROWVERSION:
				EnterOuterAlt(_localctx, 8);
				{
				State = 203; Match(DTYPE_ROWVERSION);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x31', '\xD1', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x3', '\x2', '\x3', 
		'\x2', '\a', '\x2', '\x31', '\n', '\x2', '\f', '\x2', '\xE', '\x2', '\x34', 
		'\v', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\a', '\x5', '\x42', '\n', '\x5', '\f', 
		'\x5', '\xE', '\x5', '\x45', '\v', '\x5', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\a', '\a', 'Q', '\n', '\a', '\f', '\a', 
		'\xE', '\a', 'T', '\v', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\t', '\a', '\t', '\\', '\n', '\t', '\f', '\t', 
		'\xE', '\t', '_', '\v', '\t', '\x3', '\n', '\x3', '\n', '\x5', '\n', '\x63', 
		'\n', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x5', '\n', 'k', '\n', '\n', '\x3', '\v', '\a', '\v', 
		'n', '\n', '\v', '\f', '\v', '\xE', '\v', 'q', '\v', '\v', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x5', '\r', '}', '\n', '\r', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xF', '\x3', '\xF', '\a', '\xF', '\x86', '\n', '\xF', '\f', '\xF', 
		'\xE', '\xF', '\x89', '\v', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\a', 
		'\x13', '\xA1', '\n', '\x13', '\f', '\x13', '\xE', '\x13', '\xA4', '\v', 
		'\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x5', '\x15', '\xAE', 
		'\n', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\a', '\x15', 
		'\xB3', '\n', '\x15', '\f', '\x15', '\xE', '\x15', '\xB6', '\v', '\x15', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\a', '\x16', '\xBB', '\n', 
		'\x16', '\f', '\x16', '\xE', '\x16', '\xBE', '\v', '\x16', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x5', '\x17', 
		'\xC5', '\n', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x5', 
		'\x17', '\xCF', '\n', '\x17', '\x3', '\x17', '\x2', '\x2', '\x18', '\x2', 
		'\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', '\x14', '\x16', 
		'\x18', '\x1A', '\x1C', '\x1E', ' ', '\"', '$', '&', '(', '*', ',', '\x2', 
		'\x3', '\x4', '\x2', '\a', '\a', '\x1E', '\x1E', '\x2', '\xD5', '\x2', 
		'\x32', '\x3', '\x2', '\x2', '\x2', '\x4', '\x37', '\x3', '\x2', '\x2', 
		'\x2', '\x6', ':', '\x3', '\x2', '\x2', '\x2', '\b', '\x43', '\x3', '\x2', 
		'\x2', '\x2', '\n', '\x46', '\x3', '\x2', '\x2', '\x2', '\f', 'R', '\x3', 
		'\x2', '\x2', '\x2', '\xE', 'U', '\x3', '\x2', '\x2', '\x2', '\x10', ']', 
		'\x3', '\x2', '\x2', '\x2', '\x12', '`', '\x3', '\x2', '\x2', '\x2', '\x14', 
		'o', '\x3', '\x2', '\x2', '\x2', '\x16', 'r', '\x3', '\x2', '\x2', '\x2', 
		'\x18', '|', '\x3', '\x2', '\x2', '\x2', '\x1A', '~', '\x3', '\x2', '\x2', 
		'\x2', '\x1C', '\x87', '\x3', '\x2', '\x2', '\x2', '\x1E', '\x8A', '\x3', 
		'\x2', '\x2', '\x2', ' ', '\x8F', '\x3', '\x2', '\x2', '\x2', '\"', '\x9A', 
		'\x3', '\x2', '\x2', '\x2', '$', '\xA2', '\x3', '\x2', '\x2', '\x2', '&', 
		'\xA5', '\x3', '\x2', '\x2', '\x2', '(', '\xAD', '\x3', '\x2', '\x2', 
		'\x2', '*', '\xB7', '\x3', '\x2', '\x2', '\x2', ',', '\xCE', '\x3', '\x2', 
		'\x2', '\x2', '.', '\x31', '\x5', '\x6', '\x4', '\x2', '/', '\x31', '\x5', 
		'\x4', '\x3', '\x2', '\x30', '.', '\x3', '\x2', '\x2', '\x2', '\x30', 
		'/', '\x3', '\x2', '\x2', '\x2', '\x31', '\x34', '\x3', '\x2', '\x2', 
		'\x2', '\x32', '\x30', '\x3', '\x2', '\x2', '\x2', '\x32', '\x33', '\x3', 
		'\x2', '\x2', '\x2', '\x33', '\x35', '\x3', '\x2', '\x2', '\x2', '\x34', 
		'\x32', '\x3', '\x2', '\x2', '\x2', '\x35', '\x36', '\a', '\x2', '\x2', 
		'\x3', '\x36', '\x3', '\x3', '\x2', '\x2', '\x2', '\x37', '\x38', '\a', 
		'\x31', '\x2', '\x2', '\x38', '\x39', '\b', '\x3', '\x1', '\x2', '\x39', 
		'\x5', '\x3', '\x2', '\x2', '\x2', ':', ';', '\a', '\x14', '\x2', '\x2', 
		';', '<', '\a', '-', '\x2', '\x2', '<', '=', '\a', '%', '\x2', '\x2', 
		'=', '>', '\x5', '\b', '\x5', '\x2', '>', '?', '\a', '&', '\x2', '\x2', 
		'?', '\a', '\x3', '\x2', '\x2', '\x2', '@', '\x42', '\x5', '\n', '\x6', 
		'\x2', '\x41', '@', '\x3', '\x2', '\x2', '\x2', '\x42', '\x45', '\x3', 
		'\x2', '\x2', '\x2', '\x43', '\x41', '\x3', '\x2', '\x2', '\x2', '\x43', 
		'\x44', '\x3', '\x2', '\x2', '\x2', '\x44', '\t', '\x3', '\x2', '\x2', 
		'\x2', '\x45', '\x43', '\x3', '\x2', '\x2', '\x2', '\x46', 'G', '\a', 
		'\x15', '\x2', '\x2', 'G', 'H', '\a', '-', '\x2', '\x2', 'H', 'I', '\a', 
		'%', '\x2', '\x2', 'I', 'J', '\x5', '\f', '\a', '\x2', 'J', 'K', '\a', 
		'&', '\x2', '\x2', 'K', '\v', '\x3', '\x2', '\x2', '\x2', 'L', 'Q', '\x5', 
		'\xE', '\b', '\x2', 'M', 'Q', '\x5', '\x1A', '\xE', '\x2', 'N', 'Q', '\x5', 
		'\"', '\x12', '\x2', 'O', 'Q', '\x5', '\n', '\x6', '\x2', 'P', 'L', '\x3', 
		'\x2', '\x2', '\x2', 'P', 'M', '\x3', '\x2', '\x2', '\x2', 'P', 'N', '\x3', 
		'\x2', '\x2', '\x2', 'P', 'O', '\x3', '\x2', '\x2', '\x2', 'Q', 'T', '\x3', 
		'\x2', '\x2', '\x2', 'R', 'P', '\x3', '\x2', '\x2', '\x2', 'R', 'S', '\x3', 
		'\x2', '\x2', '\x2', 'S', '\r', '\x3', '\x2', '\x2', '\x2', 'T', 'R', 
		'\x3', '\x2', '\x2', '\x2', 'U', 'V', '\a', '\x16', '\x2', '\x2', 'V', 
		'W', '\a', '%', '\x2', '\x2', 'W', 'X', '\x5', '\x10', '\t', '\x2', 'X', 
		'Y', '\a', '&', '\x2', '\x2', 'Y', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'Z', '\\', '\x5', '\x12', '\n', '\x2', '[', 'Z', '\x3', '\x2', '\x2', 
		'\x2', '\\', '_', '\x3', '\x2', '\x2', '\x2', ']', '[', '\x3', '\x2', 
		'\x2', '\x2', ']', '^', '\x3', '\x2', '\x2', '\x2', '^', '\x11', '\x3', 
		'\x2', '\x2', '\x2', '_', ']', '\x3', '\x2', '\x2', '\x2', '`', '\x62', 
		'\a', '-', '\x2', '\x2', '\x61', '\x63', '\a', '*', '\x2', '\x2', '\x62', 
		'\x61', '\x3', '\x2', '\x2', '\x2', '\x62', '\x63', '\x3', '\x2', '\x2', 
		'\x2', '\x63', '\x64', '\x3', '\x2', '\x2', '\x2', '\x64', 'j', '\x5', 
		',', '\x17', '\x2', '\x65', '\x66', '\a', '%', '\x2', '\x2', '\x66', 'g', 
		'\x5', '\x14', '\v', '\x2', 'g', 'h', '\a', '&', '\x2', '\x2', 'h', 'k', 
		'\x3', '\x2', '\x2', '\x2', 'i', 'k', '\a', '!', '\x2', '\x2', 'j', '\x65', 
		'\x3', '\x2', '\x2', '\x2', 'j', 'i', '\x3', '\x2', '\x2', '\x2', 'k', 
		'\x13', '\x3', '\x2', '\x2', '\x2', 'l', 'n', '\x5', '\x16', '\f', '\x2', 
		'm', 'l', '\x3', '\x2', '\x2', '\x2', 'n', 'q', '\x3', '\x2', '\x2', '\x2', 
		'o', 'm', '\x3', '\x2', '\x2', '\x2', 'o', 'p', '\x3', '\x2', '\x2', '\x2', 
		'p', '\x15', '\x3', '\x2', '\x2', '\x2', 'q', 'o', '\x3', '\x2', '\x2', 
		'\x2', 'r', 's', '\a', '\x19', '\x2', '\x2', 's', 't', '\a', '(', '\x2', 
		'\x2', 't', 'u', '\x5', '\x18', '\r', '\x2', 'u', 'v', '\a', '!', '\x2', 
		'\x2', 'v', '\x17', '\x3', '\x2', '\x2', '\x2', 'w', '}', '\a', '\x3', 
		'\x2', '\x2', 'x', '}', '\a', '\x4', '\x2', '\x2', 'y', 'z', '\a', '\x13', 
		'\x2', '\x2', 'z', '{', '\a', '#', '\x2', '\x2', '{', '}', '\a', '$', 
		'\x2', '\x2', '|', 'w', '\x3', '\x2', '\x2', '\x2', '|', 'x', '\x3', '\x2', 
		'\x2', '\x2', '|', 'y', '\x3', '\x2', '\x2', '\x2', '}', '\x19', '\x3', 
		'\x2', '\x2', '\x2', '~', '\x7F', '\a', '\x17', '\x2', '\x2', '\x7F', 
		'\x80', '\a', '%', '\x2', '\x2', '\x80', '\x81', '\x5', '\x1C', '\xF', 
		'\x2', '\x81', '\x82', '\a', '&', '\x2', '\x2', '\x82', '\x1B', '\x3', 
		'\x2', '\x2', '\x2', '\x83', '\x86', '\x5', '\x1E', '\x10', '\x2', '\x84', 
		'\x86', '\x5', ' ', '\x11', '\x2', '\x85', '\x83', '\x3', '\x2', '\x2', 
		'\x2', '\x85', '\x84', '\x3', '\x2', '\x2', '\x2', '\x86', '\x89', '\x3', 
		'\x2', '\x2', '\x2', '\x87', '\x85', '\x3', '\x2', '\x2', '\x2', '\x87', 
		'\x88', '\x3', '\x2', '\x2', '\x2', '\x88', '\x1D', '\x3', '\x2', '\x2', 
		'\x2', '\x89', '\x87', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', '\a', 
		'\x1A', '\x2', '\x2', '\x8B', '\x8C', '\a', '(', '\x2', '\x2', '\x8C', 
		'\x8D', '\x5', '*', '\x16', '\x2', '\x8D', '\x8E', '\a', '!', '\x2', '\x2', 
		'\x8E', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x90', '\a', '\x1B', 
		'\x2', '\x2', '\x90', '\x91', '\a', '#', '\x2', '\x2', '\x91', '\x92', 
		'\x5', '*', '\x16', '\x2', '\x92', '\x93', '\a', '$', '\x2', '\x2', '\x93', 
		'\x94', '\a', ',', '\x2', '\x2', '\x94', '\x95', '\x5', '(', '\x15', '\x2', 
		'\x95', '\x96', '\a', '#', '\x2', '\x2', '\x96', '\x97', '\x5', '*', '\x16', 
		'\x2', '\x97', '\x98', '\a', '$', '\x2', '\x2', '\x98', '\x99', '\a', 
		'!', '\x2', '\x2', '\x99', '!', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x9B', 
		'\a', '\x18', '\x2', '\x2', '\x9B', '\x9C', '\a', '%', '\x2', '\x2', '\x9C', 
		'\x9D', '\x5', '$', '\x13', '\x2', '\x9D', '\x9E', '\a', '&', '\x2', '\x2', 
		'\x9E', '#', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA1', '\x5', '&', '\x14', 
		'\x2', '\xA0', '\x9F', '\x3', '\x2', '\x2', '\x2', '\xA1', '\xA4', '\x3', 
		'\x2', '\x2', '\x2', '\xA2', '\xA0', '\x3', '\x2', '\x2', '\x2', '\xA2', 
		'\xA3', '\x3', '\x2', '\x2', '\x2', '\xA3', '%', '\x3', '\x2', '\x2', 
		'\x2', '\xA4', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA6', '\a', 
		'-', '\x2', '\x2', '\xA6', '\xA7', '\a', '#', '\x2', '\x2', '\xA7', '\xA8', 
		'\x5', '*', '\x16', '\x2', '\xA8', '\xA9', '\a', '$', '\x2', '\x2', '\xA9', 
		'\xAA', '\a', '!', '\x2', '\x2', '\xAA', '\'', '\x3', '\x2', '\x2', '\x2', 
		'\xAB', '\xAC', '\a', '-', '\x2', '\x2', '\xAC', '\xAE', '\a', '+', '\x2', 
		'\x2', '\xAD', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xAE', '\x3', 
		'\x2', '\x2', '\x2', '\xAE', '\xAF', '\x3', '\x2', '\x2', '\x2', '\xAF', 
		'\xB4', '\a', '-', '\x2', '\x2', '\xB0', '\xB1', '\a', '\"', '\x2', '\x2', 
		'\xB1', '\xB3', '\a', '-', '\x2', '\x2', '\xB2', '\xB0', '\x3', '\x2', 
		'\x2', '\x2', '\xB3', '\xB6', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB2', 
		'\x3', '\x2', '\x2', '\x2', '\xB4', '\xB5', '\x3', '\x2', '\x2', '\x2', 
		'\xB5', ')', '\x3', '\x2', '\x2', '\x2', '\xB6', '\xB4', '\x3', '\x2', 
		'\x2', '\x2', '\xB7', '\xBC', '\a', '-', '\x2', '\x2', '\xB8', '\xB9', 
		'\a', '\'', '\x2', '\x2', '\xB9', '\xBB', '\a', '-', '\x2', '\x2', '\xBA', 
		'\xB8', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xBE', '\x3', '\x2', '\x2', 
		'\x2', '\xBC', '\xBA', '\x3', '\x2', '\x2', '\x2', '\xBC', '\xBD', '\x3', 
		'\x2', '\x2', '\x2', '\xBD', '+', '\x3', '\x2', '\x2', '\x2', '\xBE', 
		'\xBC', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xCF', '\a', '\v', '\x2', 
		'\x2', '\xC0', '\xCF', '\a', '\f', '\x2', '\x2', '\xC1', '\xC4', '\a', 
		'\r', '\x2', '\x2', '\xC2', '\xC3', '\a', '\x1C', '\x2', '\x2', '\xC3', 
		'\xC5', '\a', '\x1D', '\x2', '\x2', '\xC4', '\xC2', '\x3', '\x2', '\x2', 
		'\x2', '\xC4', '\xC5', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xCF', '\x3', 
		'\x2', '\x2', '\x2', '\xC6', '\xCF', '\a', '\xE', '\x2', '\x2', '\xC7', 
		'\xC8', '\a', '\xF', '\x2', '\x2', '\xC8', '\xC9', '\a', '#', '\x2', '\x2', 
		'\xC9', '\xCA', '\t', '\x2', '\x2', '\x2', '\xCA', '\xCF', '\a', '$', 
		'\x2', '\x2', '\xCB', '\xCF', '\a', '\x10', '\x2', '\x2', '\xCC', '\xCF', 
		'\a', '\x11', '\x2', '\x2', '\xCD', '\xCF', '\a', '\x12', '\x2', '\x2', 
		'\xCE', '\xBF', '\x3', '\x2', '\x2', '\x2', '\xCE', '\xC0', '\x3', '\x2', 
		'\x2', '\x2', '\xCE', '\xC1', '\x3', '\x2', '\x2', '\x2', '\xCE', '\xC6', 
		'\x3', '\x2', '\x2', '\x2', '\xCE', '\xC7', '\x3', '\x2', '\x2', '\x2', 
		'\xCE', '\xCB', '\x3', '\x2', '\x2', '\x2', '\xCE', '\xCC', '\x3', '\x2', 
		'\x2', '\x2', '\xCE', '\xCD', '\x3', '\x2', '\x2', '\x2', '\xCF', '-', 
		'\x3', '\x2', '\x2', '\x2', '\x14', '\x30', '\x32', '\x43', 'P', 'R', 
		']', '\x62', 'j', 'o', '|', '\x85', '\x87', '\xA2', '\xAD', '\xB4', '\xBC', 
		'\xC4', '\xCE',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
