//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from KayleeParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IKayleeParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class KayleeParserBaseListener : IKayleeParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayleeParser.parse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParse([NotNull] KayleeParser.ParseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayleeParser.parse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParse([NotNull] KayleeParser.ParseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayleeParser.error"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterError([NotNull] KayleeParser.ErrorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayleeParser.error"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitError([NotNull] KayleeParser.ErrorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayleeParser.schema"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSchema([NotNull] KayleeParser.SchemaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayleeParser.schema"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSchema([NotNull] KayleeParser.SchemaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayleeParser.schemaBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSchemaBody([NotNull] KayleeParser.SchemaBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayleeParser.schemaBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSchemaBody([NotNull] KayleeParser.SchemaBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayleeParser.entity"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntity([NotNull] KayleeParser.EntityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayleeParser.entity"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntity([NotNull] KayleeParser.EntityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayleeParser.entityBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntityBody([NotNull] KayleeParser.EntityBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayleeParser.entityBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntityBody([NotNull] KayleeParser.EntityBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayleeParser.fields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFields([NotNull] KayleeParser.FieldsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayleeParser.fields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFields([NotNull] KayleeParser.FieldsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayleeParser.fieldsBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldsBody([NotNull] KayleeParser.FieldsBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayleeParser.fieldsBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldsBody([NotNull] KayleeParser.FieldsBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayleeParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField([NotNull] KayleeParser.FieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayleeParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField([NotNull] KayleeParser.FieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayleeParser.fieldBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldBody([NotNull] KayleeParser.FieldBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayleeParser.fieldBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldBody([NotNull] KayleeParser.FieldBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayleeParser.fieldParameterDefault"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldParameterDefault([NotNull] KayleeParser.FieldParameterDefaultContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayleeParser.fieldParameterDefault"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldParameterDefault([NotNull] KayleeParser.FieldParameterDefaultContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayleeParser.fieldParameterDefaultValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldParameterDefaultValue([NotNull] KayleeParser.FieldParameterDefaultValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayleeParser.fieldParameterDefaultValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldParameterDefaultValue([NotNull] KayleeParser.FieldParameterDefaultValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayleeParser.entityKeys"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntityKeys([NotNull] KayleeParser.EntityKeysContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayleeParser.entityKeys"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntityKeys([NotNull] KayleeParser.EntityKeysContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayleeParser.entityKeysBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntityKeysBody([NotNull] KayleeParser.EntityKeysBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayleeParser.entityKeysBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntityKeysBody([NotNull] KayleeParser.EntityKeysBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayleeParser.entityKeyPrimary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntityKeyPrimary([NotNull] KayleeParser.EntityKeyPrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayleeParser.entityKeyPrimary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntityKeyPrimary([NotNull] KayleeParser.EntityKeyPrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayleeParser.entityKeyReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntityKeyReference([NotNull] KayleeParser.EntityKeyReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayleeParser.entityKeyReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntityKeyReference([NotNull] KayleeParser.EntityKeyReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayleeParser.mutations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMutations([NotNull] KayleeParser.MutationsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayleeParser.mutations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMutations([NotNull] KayleeParser.MutationsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayleeParser.mutationsBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMutationsBody([NotNull] KayleeParser.MutationsBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayleeParser.mutationsBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMutationsBody([NotNull] KayleeParser.MutationsBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayleeParser.mutation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMutation([NotNull] KayleeParser.MutationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayleeParser.mutation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMutation([NotNull] KayleeParser.MutationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayleeParser.qualified"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQualified([NotNull] KayleeParser.QualifiedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayleeParser.qualified"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQualified([NotNull] KayleeParser.QualifiedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayleeParser.identifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifierList([NotNull] KayleeParser.IdentifierListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayleeParser.identifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifierList([NotNull] KayleeParser.IdentifierListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayleeParser.dtype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDtype([NotNull] KayleeParser.DtypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayleeParser.dtype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDtype([NotNull] KayleeParser.DtypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayleeParser.dtypeIntAutoIncrement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDtypeIntAutoIncrement([NotNull] KayleeParser.DtypeIntAutoIncrementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayleeParser.dtypeIntAutoIncrement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDtypeIntAutoIncrement([NotNull] KayleeParser.DtypeIntAutoIncrementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="KayleeParser.dtypeTextSize"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDtypeTextSize([NotNull] KayleeParser.DtypeTextSizeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="KayleeParser.dtypeTextSize"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDtypeTextSize([NotNull] KayleeParser.DtypeTextSizeContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
